export interface Env {
  GAME_DB: D1Database;
  GAME_ASSETS: R2Bucket;
  GAME_ROOMS?: DurableObjectNamespace;
  ASSETS?: Fetcher;
  ADMIN_SETUP_KEY?: string;
  APP_NAME?: string;
  MAIN_SITE_URL?: string;
}

type AccountRow = { id:string; email:string; display_name:string; password_hash:string; password_salt:string; is_admin:number; status:string; created_at:string; updated_at:string };

const json = (data:unknown, status=200, headers:HeadersInit={}) => new Response(JSON.stringify(data), { status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers} });
const fail = (message:string,status=400) => json({error:message},status);
const now = () => new Date().toISOString();
const id = (prefix:string) => `${prefix}_${crypto.randomUUID()}`;
const enc = new TextEncoder();
function bytesToB64(bytes:Uint8Array){ let s=''; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s); }
function b64ToBytes(s:string){ const raw=atob(s); return Uint8Array.from(raw,c=>c.charCodeAt(0)); }
function toHex(buf:ArrayBuffer){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password:string,saltB64?:string){ const salt=saltB64?b64ToBytes(saltB64):crypto.getRandomValues(new Uint8Array(16)); const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:100000},key,256); return {hash:bytesToB64(new Uint8Array(bits)),salt:bytesToB64(salt)}; }
async function hashToken(token:string){return toHex(await crypto.subtle.digest('SHA-256',enc.encode(token)))}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(24));return bytesToB64(b).replace(/[+/=]/g,'').slice(0,32)}
function randomCode(len=6){let out='';const b=crypto.getRandomValues(new Uint8Array(len));for(const x of b)out+=(x%10);return out}
async function body<T=any>(req:Request):Promise<T>{try{return await req.json() as T}catch{throw new Error('JSON không hợp lệ')}}
function accountDto(a:AccountRow){return {id:a.id,email:a.email,displayName:a.display_name,isAdmin:!!a.is_admin,status:a.status}}

async function getAccountFromRequest(req:Request,env:Env):Promise<AccountRow|null>{ const auth=req.headers.get('authorization')||''; if(!auth.startsWith('Bearer '))return null; const token=auth.slice(7); if(!token)return null; const tokenHash=await hashToken(token); const row=await env.GAME_DB.prepare(`SELECT a.* FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.expires_at>? AND a.status='active' LIMIT 1`).bind(tokenHash,now()).first<AccountRow>(); return row||null; }
async function requireAccount(req:Request,env:Env,admin=false){const a=await getAccountFromRequest(req,env);if(!a)throw new Response(JSON.stringify({error:'Bạn chưa đăng nhập.'}),{status:401,headers:{'content-type':'application/json'}});if(admin&&!a.is_admin)throw new Response(JSON.stringify({error:'Yêu cầu quyền quản trị.'}),{status:403,headers:{'content-type':'application/json'}});return a}
async function createSession(env:Env,accountId:string){const token=randomToken();const tokenHash=await hashToken(token);const expires=new Date(Date.now()+1000*60*60*24*14).toISOString();await env.GAME_DB.prepare('INSERT INTO sessions (id,account_id,token_hash,expires_at,created_at) VALUES (?,?,?,?,?)').bind(id('ses'),accountId,tokenHash,expires,now()).run();return token}

async function getSettings(env:Env){ const rows=await env.GAME_DB.prepare('SELECT key,value_json FROM settings').all<{key:string;value_json:string}>(); const out:Record<string,any>={}; for(const r of rows.results||[]){try{out[r.key]=JSON.parse(r.value_json)}catch{out[r.key]=r.value_json}} return out; }
async function publicConfig(env:Env){const all=await getSettings(env);const site=all.site||{};const home=all.homepage||{};const footer=all.footer||{};const seo=all.seo||{};const system=all.system||{};const navigation=all.navigation||{};const branding=all.branding||{};const pages=all.pages||{};return {brandName:site.brandName||'Sky First Games',shortName:site.shortName||'SFG',tagline:site.tagline||'Play. Learn. Level Up.',heroTitle:home.heroTitle||'Chơi để học. Học để đi xa hơn.',heroSubtitle:home.heroSubtitle||'Hệ sinh thái trò chơi học tập đa ngôn ngữ của Sky First.',mainSiteUrl:site.mainSiteUrl||env.MAIN_SITE_URL||'https://skyfirst.io.vn',mainSiteLabel:site.mainSiteLabel||'Website chính — Sky First Network',announcement:home.announcement||'',maintenance:!!system.maintenance,primaryCta:'Chơi ngay',footerAbout:footer.about||'Sky First Games là sản phẩm trò chơi học tập thuộc hệ sinh thái Sky First Network.',seoTitle:seo.title||'Sky First Games',seoDescription:seo.description||'',contactEmail:site.contactEmail||'hotro.sfn@gmail.com',navigationItems:navigation.items||[],footerLinks:footer.links||[],homepageSections:home.sections||['featured','languages','creator'],primaryColor:branding.primary||'#0ea5e9',navyColor:branding.navy||'#07182f',borderRadius:branding.radius||'22px',customPages:pages,logoUrl:branding.logoUrl||'/brand/sky-first-logo.png',footerPortals:footer.portals||[],footerCopyright:footer.copyright||'© 2026 Sky First Games — Bản quyền thuộc Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',footerEcosystemLine:footer.ecosystemLine||'Một sản phẩm thuộc hệ sinh thái Sky First Network.',languageItems:all.languages?.items||[]};}

async function listQuestionSets(env:Env,ownerId?:string){
 let sql=`SELECT qs.*, (SELECT COUNT(*) FROM questions q WHERE q.set_id=qs.id) AS question_count FROM question_sets qs`;
 const binds:any[]=[];
 if(ownerId){sql+=` WHERE qs.created_by=?`;binds.push(ownerId)}else sql+=` WHERE qs.status='published' AND qs.visibility='public'`;
 sql+=' ORDER BY qs.updated_at DESC';
 const rows=await env.GAME_DB.prepare(sql).bind(...binds).all<any>();
 const result=[] as any[];
 for(const s of rows.results||[]){const qs=await env.GAME_DB.prepare('SELECT * FROM questions WHERE set_id=? ORDER BY sort_order,id').bind(s.id).all<any>();result.push({id:s.id,title:s.title,language:s.language,level:s.level,topic:s.topic,context:s.context||'Daily Life',skill:s.skill||'Mixed',description:s.description||'',isOfficial:!!s.is_official,visibility:s.visibility,status:s.status,updatedAt:s.updated_at,questions:(qs.results||[]).map(q=>({id:q.id,type:q.type,prompt:q.prompt,options:JSON.parse(q.options_json||'[]'),answers:JSON.parse(q.answers_json||'[]'),pairs:JSON.parse(q.pairs_json||'[]'),explanation:q.explanation||'',hint:q.hint||'',mediaUrl:q.media_url||'',mediaType:q.media_type||undefined,transcript:q.transcript||'',ttsText:q.tts_text||'',ttsLang:q.tts_lang||'',maxPlays:q.max_plays||undefined,playbackRate:q.playback_rate||1,passage:q.passage||'',context:q.context||'',difficulty:q.difficulty||1,tags:JSON.parse(q.tags_json||'[]')}))})}
 return result;
}


async function getQuestionSetById(env:Env,setId:string){
 const s=await env.GAME_DB.prepare('SELECT * FROM question_sets WHERE id=? LIMIT 1').bind(setId).first<any>();
 if(!s)return null;
 const qs=await env.GAME_DB.prepare('SELECT * FROM questions WHERE set_id=? ORDER BY sort_order,id').bind(setId).all<any>();
 return {id:s.id,title:s.title,language:s.language,level:s.level,topic:s.topic,description:s.description||'',isOfficial:!!s.is_official,visibility:s.visibility,updatedAt:s.updated_at,questions:(qs.results||[]).map(q=>({id:q.id,type:q.type,prompt:q.prompt,options:JSON.parse(q.options_json||'[]'),answers:JSON.parse(q.answers_json||'[]'),pairs:JSON.parse(q.pairs_json||'[]'),explanation:q.explanation||'',hint:q.hint||'',mediaUrl:q.media_url||'',difficulty:q.difficulty||1,tags:JSON.parse(q.tags_json||'[]')}))};
}

export async function apiRequest(req:Request,env:Env):Promise<Response>{
 const u=new URL(req.url);const p=u.pathname;const method=req.method.toUpperCase();
 try{
  if(p==='/api/health')return json({ok:true,app:env.APP_NAME||'Sky First Games',time:now()});
  if(p==='/api/public/config'&&method==='GET')return json({config:await publicConfig(env)});
  if(p==='/api/public/game-modes'&&method==='GET'){const rows=await env.GAME_DB.prepare(`SELECT * FROM game_modes WHERE status IN ('active','beta','seasonal') ORDER BY sort_order,name`).all<any>();return json({modes:(rows.results||[]).map(m=>({id:m.id,name:m.name,family:m.family,icon:m.icon,description:m.description,supportedQuestionTypes:JSON.parse(m.supported_question_types_json||'[]'),sessionModes:JSON.parse(m.session_modes_json||'[]'),minPlayers:m.min_players,maxPlayers:m.max_players,durationMinutes:JSON.parse(m.duration_minutes_json||'[3,15]'),languages:m.languages_json==='"universal"'?'universal':JSON.parse(m.languages_json||'[]'),status:m.status,featured:!!m.featured,color:m.color,mechanic:m.mechanic}))});}
  if(p==='/api/public/question-sets'&&method==='GET')return json({sets:await listQuestionSets(env)});

  const publicGame=p.match(/^\/api\/public\/games\/([^/]+)$/);if(publicGame&&method==='GET'){const code=decodeURIComponent(publicGame[1]);const game=await env.GAME_DB.prepare("SELECT * FROM games WHERE join_code=? AND status='active' LIMIT 1").bind(code).first<any>();if(!game)return fail('Không tìm thấy trò chơi hoặc trò chơi đã đóng.',404);const set=await getQuestionSetById(env,game.set_id);if(!set)return fail('Bộ câu hỏi không còn tồn tại.',404);const activeSession=await env.GAME_DB.prepare("SELECT id,room_code,state FROM game_sessions WHERE game_id=? AND state='running' ORDER BY created_at DESC LIMIT 1").bind(game.id).first<any>();return json({game,set,activeSession:activeSession||null})}
  const hostPass=p.match(/^\/api\/host\/pass\/([^/]+)$/);if(hostPass&&method==='GET'){const token=decodeURIComponent(hostPass[1]);const pass=await env.GAME_DB.prepare('SELECT * FROM access_passes WHERE token=? AND revoked_at IS NULL LIMIT 1').bind(token).first<any>();if(!pass)return fail('Access Pass không hợp lệ hoặc đã bị thu hồi.',403);if(pass.expires_at&&pass.expires_at<now())return fail('Access Pass đã hết hạn.',403);if(pass.pin_hash){const pin=u.searchParams.get('pin')||'';const hp=await hashPassword(pin,pass.pin_salt);if(hp.hash!==pass.pin_hash)return fail('PIN Host chưa đúng.',401)}const game=await env.GAME_DB.prepare('SELECT * FROM games WHERE id=?').bind(pass.game_id).first<any>();if(!game)return fail('Game không tồn tại.',404);const set=await getQuestionSetById(env,game.set_id);if(!set)return fail('Bộ câu hỏi không tồn tại.',404);const safePass={...pass,pin_hash:undefined,pin_salt:undefined};return json({pass:safePass,game,set})}
  const hostSession=p.match(/^\/api\/host\/pass\/([^/]+)\/sessions$/);if(hostSession&&method==='POST'){const token=decodeURIComponent(hostSession[1]);const pass=await env.GAME_DB.prepare('SELECT * FROM access_passes WHERE token=? AND revoked_at IS NULL LIMIT 1').bind(token).first<any>();if(!pass)return fail('Access Pass không hợp lệ hoặc đã bị thu hồi.',403);if(pass.expires_at&&pass.expires_at<now())return fail('Access Pass đã hết hạn.',403);if(pass.pin_hash){const pin=u.searchParams.get('pin')||'';const hp=await hashPassword(pin,pass.pin_salt);if(hp.hash!==pass.pin_hash)return fail('PIN Host chưa đúng.',401)}const permissions=JSON.parse(pass.permissions_json||'[]');if(!permissions.includes('host'))return fail('Access Pass không có quyền host.',403);const game=await env.GAME_DB.prepare('SELECT * FROM games WHERE id=?').bind(pass.game_id).first<any>();if(!game)return fail('Game không tồn tại.',404);const set=await getQuestionSetById(env,game.set_id);if(!set)return fail('Bộ câu hỏi không tồn tại.',404);const sid=id('gs');const room=randomCode(6);await env.GAME_DB.prepare(`INSERT INTO game_sessions (id,game_id,mode_id,question_snapshot_json,config_snapshot_json,state,room_code,started_at,created_at) VALUES (?,?,?,?,?,'running',?,?,?)`).bind(sid,game.id,game.mode_id,JSON.stringify(set),game.config_json||'{}',room,now(),now()).run();const session=await env.GAME_DB.prepare('SELECT * FROM game_sessions WHERE id=?').bind(sid).first<any>();if(env.GAME_ROOMS){const roomId=env.GAME_ROOMS.idFromName(sid);const stub=env.GAME_ROOMS.get(roomId);await stub.fetch(new Request('https://room/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:sid,gameId:game.id,roomCode:room,modeId:game.mode_id,state:'running',players:[]})}));}return json({session,livePath:env.GAME_ROOMS?`/api/live/${sid}`:null},201)}

  if(p==='/api/auth/status'&&method==='GET'){const r=await env.GAME_DB.prepare('SELECT COUNT(*) AS c FROM accounts').first<any>();return json({initialized:Number(r?.c||0)>0})}
  if(p==='/api/auth/bootstrap'&&method==='POST'){const c=await env.GAME_DB.prepare('SELECT COUNT(*) AS c FROM accounts').first<any>();if(Number(c?.c||0)>0)return fail('Hệ thống đã được khởi tạo.',409);const b=await body<any>(req);if(!env.ADMIN_SETUP_KEY||b.setupKey!==env.ADMIN_SETUP_KEY)return fail('Setup key không đúng.',403);if(!b.email||!b.password||!b.displayName)return fail('Thiếu thông tin.',400);const hp=await hashPassword(b.password);const aid=id('acc');await env.GAME_DB.prepare(`INSERT INTO accounts (id,email,display_name,password_hash,password_salt,is_admin,status,created_at,updated_at) VALUES (?,?,?,?,?,1,'active',?,?)`).bind(aid,String(b.email).toLowerCase(),b.displayName,hp.hash,hp.salt,now(),now()).run();const a=await env.GAME_DB.prepare('SELECT * FROM accounts WHERE id=?').bind(aid).first<AccountRow>();const token=await createSession(env,aid);return json({token,account:accountDto(a!)},201)}
  if(p==='/api/auth/register'&&method==='POST'){const settings=await getSettings(env);if(settings.system?.selfCreatorRegistration===false)return fail('Tự khởi tạo tài khoản Creator đang tạm tắt.',403);const b=await body<any>(req);const email=String(b.email||'').trim().toLowerCase();const displayName=String(b.displayName||'').trim();const password=String(b.password||'');if(!email||!displayName||password.length<8)return fail('Vui lòng nhập tên, email và mật khẩu tối thiểu 8 ký tự.',400);const exists=await env.GAME_DB.prepare('SELECT id FROM accounts WHERE lower(email)=lower(?) LIMIT 1').bind(email).first<any>();if(exists)return fail('Email này đã có tài khoản.',409);const hp=await hashPassword(password);const aid=id('acc');await env.GAME_DB.prepare(`INSERT INTO accounts (id,email,display_name,password_hash,password_salt,is_admin,status,created_at,updated_at) VALUES (?,?,?,?,?,0,'active',?,?)`).bind(aid,email,displayName,hp.hash,hp.salt,now(),now()).run();const a=await env.GAME_DB.prepare('SELECT * FROM accounts WHERE id=?').bind(aid).first<AccountRow>();const token=await createSession(env,aid);return json({token,account:accountDto(a!)},201)}
  if(p==='/api/auth/login'&&method==='POST'){const b=await body<any>(req);const a=await env.GAME_DB.prepare('SELECT * FROM accounts WHERE lower(email)=lower(?) LIMIT 1').bind(b.email||'').first<AccountRow>();if(!a||a.status!=='active')return fail('Email hoặc mật khẩu không đúng.',401);const hp=await hashPassword(b.password||'',a.password_salt);if(hp.hash!==a.password_hash)return fail('Email hoặc mật khẩu không đúng.',401);const token=await createSession(env,a.id);return json({token,account:accountDto(a)})}
  if(p==='/api/auth/me'&&method==='GET'){const a=await requireAccount(req,env);return json({account:accountDto(a)})}
  if(p==='/api/auth/logout'&&method==='POST'){const auth=req.headers.get('authorization')||'';if(auth.startsWith('Bearer ')){const h=await hashToken(auth.slice(7));await env.GAME_DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(h).run()}return json({ok:true})}

  if(p==='/api/creator/question-sets'&&method==='GET'){const a=await requireAccount(req,env);return json({sets:await listQuestionSets(env,a.id)})}
  if(p==='/api/creator/question-sets'&&method==='POST'){const a=await requireAccount(req,env);const b=await body<any>(req);const setId=b.id&&String(b.id).startsWith('set_')?b.id:id('set');const exists=await env.GAME_DB.prepare('SELECT id FROM question_sets WHERE id=? AND created_by=?').bind(setId,a.id).first<any>();if(exists){await env.GAME_DB.prepare(`UPDATE question_sets SET title=?,language=?,level=?,topic=?,context=?,skill=?,description=?,visibility=?,updated_at=?,version=version+1 WHERE id=?`).bind(b.title||'Untitled',b.language||'en',b.level||'',b.topic||'',b.context||'Daily Life',b.skill||'Mixed',b.description||'',b.visibility||'private',now(),setId).run();await env.GAME_DB.prepare('DELETE FROM questions WHERE set_id=?').bind(setId).run()}else{await env.GAME_DB.prepare(`INSERT INTO question_sets (id,title,language,level,topic,context,skill,description,is_official,visibility,status,version,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,0,?,'draft',1,?,?,?)`).bind(setId,b.title||'Untitled',b.language||'en',b.level||'',b.topic||'',b.context||'Daily Life',b.skill||'Mixed',b.description||'',b.visibility||'private',a.id,now(),now()).run()}
   const questions=Array.isArray(b.questions)?b.questions:[];let sort=0;for(const q of questions){await env.GAME_DB.prepare(`INSERT INTO questions (id,set_id,type,prompt,options_json,answers_json,pairs_json,explanation,hint,media_url,media_type,transcript,tts_text,tts_lang,max_plays,playback_rate,passage,context,difficulty,tags_json,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(q.id||id('q'),setId,q.type||'multiple_choice',q.prompt||'',JSON.stringify(q.options||[]),JSON.stringify(q.answers||[]),JSON.stringify(q.pairs||[]),q.explanation||'',q.hint||'',q.mediaUrl||'',q.mediaType||'',q.transcript||'',q.ttsText||'',q.ttsLang||'',q.maxPlays||0,q.playbackRate||1,q.passage||'',q.context||'',q.difficulty||1,JSON.stringify(q.tags||[]),sort++,now(),now()).run()}
   const out=(await listQuestionSets(env,a.id)).find(s=>s.id===setId);return json({set:out},201)}
  const setDelete=p.match(/^\/api\/creator\/question-sets\/([^/]+)$/);if(setDelete&&method==='DELETE'){const a=await requireAccount(req,env);const sid=decodeURIComponent(setDelete[1]);await env.GAME_DB.prepare('DELETE FROM questions WHERE set_id IN (SELECT id FROM question_sets WHERE id=? AND created_by=?)').bind(sid,a.id).run();await env.GAME_DB.prepare('DELETE FROM question_sets WHERE id=? AND created_by=?').bind(sid,a.id).run();return json({ok:true})}

  if(p==='/api/creator/games'&&method==='GET'){const a=await requireAccount(req,env);const rows=await env.GAME_DB.prepare('SELECT * FROM games WHERE created_by=? ORDER BY created_at DESC').bind(a.id).all<any>();return json({games:rows.results||[]})}
  if(p==='/api/creator/games'&&method==='POST'){const a=await requireAccount(req,env);const b=await body<any>(req);let code=randomCode();for(let i=0;i<3;i++){const ex=await env.GAME_DB.prepare('SELECT id FROM games WHERE join_code=?').bind(code).first<any>();if(!ex)break;code=randomCode()}const gid=id('game');await env.GAME_DB.prepare(`INSERT INTO games (id,title,mode_id,set_id,visibility,join_code,config_json,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'active',?,?,?)`).bind(gid,b.title||'Untitled Game',b.modeId,b.setId,b.visibility||'link',code,JSON.stringify(b.config||{}),a.id,now(),now()).run();const g=await env.GAME_DB.prepare('SELECT * FROM games WHERE id=?').bind(gid).first<any>();return json({game:g},201)}

  if(p==='/api/creator/access-passes'&&method==='GET'){const a=await requireAccount(req,env);const rows=await env.GAME_DB.prepare('SELECT ap.* FROM access_passes ap JOIN games g ON g.id=ap.game_id WHERE g.created_by=? ORDER BY ap.created_at DESC').bind(a.id).all<any>();return json({passes:rows.results||[]})}
  if(p==='/api/creator/access-passes'&&method==='POST'){const a=await requireAccount(req,env);const b=await body<any>(req);const game=await env.GAME_DB.prepare('SELECT * FROM games WHERE id=? AND created_by=?').bind(b.gameId,a.id).first<any>();if(!game)return fail('Không tìm thấy game.',404);const rawPin=String(b.pin||randomCode(4));const php=await hashPassword(rawPin);const pass={id:id('pass'),token:randomToken(),label:b.label||'TNV Host',permissions:JSON.stringify(b.permissions||['host']),expiresAt:b.expiresAt||null};await env.GAME_DB.prepare(`INSERT INTO access_passes (id,game_id,token,label,permissions_json,expires_at,created_at,pin_hash,pin_salt) VALUES (?,?,?,?,?,?,?,?,?)`).bind(pass.id,b.gameId,pass.token,pass.label,pass.permissions,pass.expiresAt,now(),php.hash,php.salt).run();const row=await env.GAME_DB.prepare('SELECT id,game_id,token,label,permissions_json,expires_at,created_at,revoked_at FROM access_passes WHERE id=?').bind(pass.id).first<any>();return json({pass:row,pin:rawPin},201)}
  const passDel=p.match(/^\/api\/creator\/access-passes\/([^/]+)$/);if(passDel&&method==='DELETE'){const a=await requireAccount(req,env);await env.GAME_DB.prepare(`UPDATE access_passes SET revoked_at=? WHERE id=? AND game_id IN (SELECT id FROM games WHERE created_by=?)`).bind(now(),decodeURIComponent(passDel[1]),a.id).run();return json({ok:true})}

  if(p==='/api/admin/settings'&&method==='GET'){await requireAccount(req,env,true);return json({settings:await getSettings(env)})}
  const setting=p.match(/^\/api\/admin\/settings\/([^/]+)$/);if(setting&&method==='PUT'){const a=await requireAccount(req,env,true);const key=decodeURIComponent(setting[1]);const b=await body<any>(req);await env.GAME_DB.prepare(`INSERT INTO settings (key,value_json,updated_at,updated_by) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(key,JSON.stringify(b.value),now(),a.id).run();return json({ok:true})}
  if(p==='/api/admin/game-modes'&&method==='GET'){await requireAccount(req,env,true);const rows=await env.GAME_DB.prepare('SELECT * FROM game_modes ORDER BY sort_order,name').all<any>();return json({modes:rows.results||[]})}
  const modePath=p.match(/^\/api\/admin\/game-modes\/([^/]+)$/);if(modePath&&method==='PUT'){await requireAccount(req,env,true);const b=await body<any>(req);const allowed=['name','description','status','color','icon','version','featured','sort_order'];const entries=Object.entries(b).filter(([k])=>allowed.includes(k));if(!entries.length)return fail('Không có trường hợp lệ.');const sql=`UPDATE game_modes SET ${entries.map(([k])=>`${k}=?`).join(',')},updated_at=? WHERE id=?`;await env.GAME_DB.prepare(sql).bind(...entries.map(([,v])=>v),now(),decodeURIComponent(modePath[1])).run();return json({ok:true})}

  if(p==='/api/admin/sessions'&&method==='GET'){await requireAccount(req,env,true);const rows=await env.GAME_DB.prepare('SELECT gs.*, g.title AS game_title FROM game_sessions gs JOIN games g ON g.id=gs.game_id ORDER BY gs.created_at DESC LIMIT 200').all<any>();return json({sessions:rows.results||[]})}

  if(p==='/api/admin/accounts'&&method==='GET'){await requireAccount(req,env,true);const rows=await env.GAME_DB.prepare('SELECT id,email,display_name,is_admin,status,created_at,updated_at FROM accounts ORDER BY created_at DESC').all<any>();return json({accounts:rows.results||[]})}
  if(p==='/api/admin/accounts'&&method==='POST'){await requireAccount(req,env,true);const b=await body<any>(req);if(!b.email||!b.displayName||!b.password)return fail('Thiếu email, tên hoặc mật khẩu.');const hp=await hashPassword(b.password);const aid=id('acc');await env.GAME_DB.prepare(`INSERT INTO accounts (id,email,display_name,password_hash,password_salt,is_admin,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'active',?,?)`).bind(aid,String(b.email).toLowerCase(),b.displayName,hp.hash,hp.salt,b.isAdmin?1:0,now(),now()).run();const a=await env.GAME_DB.prepare('SELECT * FROM accounts WHERE id=?').bind(aid).first<AccountRow>();return json({account:accountDto(a!)},201)}
  const accountPath=p.match(/^\/api\/admin\/accounts\/([^/]+)$/);if(accountPath&&method==='PUT'){await requireAccount(req,env,true);const b=await body<any>(req);const aid=decodeURIComponent(accountPath[1]);if(b.status)await env.GAME_DB.prepare('UPDATE accounts SET status=?,updated_at=? WHERE id=?').bind(b.status,now(),aid).run();if(typeof b.isAdmin==='boolean')await env.GAME_DB.prepare('UPDATE accounts SET is_admin=?,updated_at=? WHERE id=?').bind(b.isAdmin?1:0,now(),aid).run();return json({ok:true})}
  if(p==='/api/media'&&method==='POST'){await requireAccount(req,env);const name=(u.searchParams.get('name')||'asset.bin').replace(/[^a-zA-Z0-9._-]/g,'_');const key=`uploads/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${name}`;await env.GAME_ASSETS.put(key,req.body,{httpMetadata:{contentType:req.headers.get('content-type')||'application/octet-stream'}});return json({key,url:`/media/${key}`},201)}
  if(p==='/api/admin/media'&&method==='POST'){await requireAccount(req,env,true);const name=(u.searchParams.get('name')||'asset.bin').replace(/[^a-zA-Z0-9._-]/g,'_');const key=`uploads/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${name}`;await env.GAME_ASSETS.put(key,req.body,{httpMetadata:{contentType:req.headers.get('content-type')||'application/octet-stream'}});return json({key,url:`/media/${key}`},201)}
  return fail('API route không tồn tại.',404);
 }catch(e:any){if(e instanceof Response)return e;console.error(e);return fail(e?.message||'Internal error',500)}
}


async function liveProxy(req:Request,env:Env){
 const u=new URL(req.url);const m=u.pathname.match(/^\/api\/live\/([^/]+)$/);if(!m)return fail('Live room không hợp lệ.',404);const sessionId=decodeURIComponent(m[1]);const session=await env.GAME_DB.prepare('SELECT * FROM game_sessions WHERE id=? LIMIT 1').bind(sessionId).first<any>();if(!session)return fail('Session không tồn tại.',404);
 const role=u.searchParams.get('role')||'player';
 if(role==='host'){const token=u.searchParams.get('pass')||'';const pass=await env.GAME_DB.prepare('SELECT * FROM access_passes WHERE token=? AND game_id=? AND revoked_at IS NULL LIMIT 1').bind(token,session.game_id).first<any>();if(!pass)return fail('Không có quyền host live room.',403)}
 if(!env.GAME_ROOMS)return fail('Realtime room chưa được bind.',503);const rid=env.GAME_ROOMS.idFromName(sessionId);const stub=env.GAME_ROOMS.get(rid);const h=new Headers(req.headers);h.set('x-sfg-role',role);return stub.fetch(new Request('https://room/ws',{method:req.method,headers:h,body:req.body}));
}

export class GameRoom {
 constructor(private ctx:DurableObjectState, private env:Env){}
 async fetch(req:Request):Promise<Response>{
  const u=new URL(req.url);
  if(u.pathname==='/init'&&req.method==='POST'){const data=await req.json<any>();await this.ctx.storage.put('meta',data);return json({ok:true})}
  if(u.pathname==='/state'){const meta=await this.ctx.storage.get<any>('meta');const players=(await this.ctx.storage.get<any[]>('players'))||[];return json({meta,players})}
  if(u.pathname==='/ws'&&req.headers.get('upgrade')?.toLowerCase()==='websocket'){
    const pair=new WebSocketPair();const client=pair[0],server=pair[1];const role=req.headers.get('x-sfg-role')||'player';this.ctx.acceptWebSocket(server,[role]);const meta=await this.ctx.storage.get<any>('meta');const players=(await this.ctx.storage.get<any[]>('players'))||[];server.send(JSON.stringify({type:'snapshot',meta,players}));return new Response(null,{status:101,webSocket:client});
  }
  return fail('Room route không tồn tại.',404)
 }
 async webSocketMessage(ws:WebSocket,message:string|ArrayBuffer){
   if(typeof message!=='string')return;let data:any;try{data=JSON.parse(message)}catch{return}
   if(data.type==='join'){
     const players=(await this.ctx.storage.get<any[]>('players'))||[];const nickname=String(data.nickname||'Player').slice(0,40);const entry={id:crypto.randomUUID(),nickname,joinedAt:now()};players.push(entry);await this.ctx.storage.put('players',players.slice(-200));this.broadcast({type:'roster',players:players.slice(-200)});return;
   }
   if(data.type==='host-event'){
     const tags=this.ctx.getTags(ws);if(!tags.includes('host'))return;const meta=(await this.ctx.storage.get<any>('meta'))||{};const next={...meta,lastEvent:data.event,updatedAt:now()};await this.ctx.storage.put('meta',next);this.broadcast({type:'host-event',event:data.event,meta:next});
   }
 }
 async webSocketClose(ws:WebSocket,code:number,reason:string,wasClean:boolean){try{ws.close(code,reason)}catch{}}
 private broadcast(payload:any){const text=JSON.stringify(payload);for(const ws of this.ctx.getWebSockets()){try{ws.send(text)}catch{}}}
}

export default {
 async fetch(req:Request,env:Env):Promise<Response>{const u=new URL(req.url);if(u.pathname.startsWith('/api/live/'))return liveProxy(req,env);if(u.pathname.startsWith('/api/'))return apiRequest(req,env);if(u.pathname.startsWith('/media/')){const key=decodeURIComponent(u.pathname.slice('/media/'.length));const obj=await env.GAME_ASSETS.get(key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set('etag',obj.httpEtag);h.set('cache-control','public, max-age=31536000, immutable');return new Response(obj.body,{headers:h})}return env.ASSETS?env.ASSETS.fetch(req):new Response('Not found',{status:404})}
} satisfies ExportedHandler<Env>;
