import React from 'react';
import { Activity, Bell, BookOpen, Boxes, Braces, Database, FileText, Gamepad2, Globe2, Image, KeyRound, Languages, LayoutDashboard, Link2, ListChecks, Menu, Palette, Radio, Save, Search, Settings, ShieldCheck, SlidersHorizontal, ToggleLeft, UploadCloud, UserCog, Users, Wrench, LifeBuoy, QrCode, Copyright, LockKeyhole, Download, Trash2, CheckCircle2, XCircle } from 'lucide-react';
import { api } from '../lib/api';
import { gameModes as builtInModes } from '../data/gameModes';
import { languages as builtInLanguages } from '../data/languages';
import { seedQuestionSets } from '../data/seedContent';
import { infoPages } from '../data/infoPages';
import type { Account } from '../types';

type Tab='overview'|'website'|'navigation'|'join'|'volunteer'|'pages'|'languages'|'games'|'content'|'accounts'|'access'|'sessions'|'media'|'support'|'security'|'system';
const tabs:[Tab,string,React.ReactNode][]=[['overview','Command Center',<LayoutDashboard/>],['website','Website Studio',<Palette/>],['navigation','Menu & Footer',<Menu/>],['join','Join & QR',<QrCode/>],['volunteer','TNV Hub',<Users/>],['pages','Trang thông tin',<FileText/>],['languages','Ngôn ngữ',<Languages/>],['games','Game Modes',<Gamepad2/>],['content','Content Engine',<BookOpen/>],['accounts','Tài khoản',<UserCog/>],['access','Access Pass',<KeyRound/>],['sessions','Live & Sessions',<Radio/>],['media','R2 Media',<Image/>],['support','Support Center',<LifeBuoy/>],['security','An toàn & Bảo mật',<LockKeyhole/>],['system','System Control',<Settings/>]];

const defaults:any={
 website:{brandName:'Sky First Games',tagline:'PLAY • LEARN • LEVEL UP',heroTitle:'Play. Learn. Level Up.',heroSubtitle:'Nền tảng trò chơi học tập đa ngôn ngữ của Sky First.',contactEmail:'hotro.sfn@gmail.com',mainSiteUrl:'https://skyfirst.io.vn',primaryColor:'#0ea5e9',navyColor:'#07182f'},
 navigation:{main:['Trang chủ','Khám phá','Tham gia','Tình nguyện viên','Tổng quan'],overview:Object.values(infoPages).map(x=>({label:x.title,url:`/info/${x.slug}`,enabled:true})),footerLanguageDropdown:true},
 join:{code:true,cameraQr:true,uploadQr:true,directLink:true,requireName:true,maxPlayers:60,allowLateJoin:true,safeNickname:true,codeLength:6,cameraMessage:'Cho phép camera để quét QR.'},
 volunteer:{enabled:true,gallery:true,uploadsRequireReview:true,reportEnabled:true,announcements:true,hostByAccessPass:true},
 security:{rateLimit:true,serverScoring:true,hideAnswersBeforeReveal:true,safeNickname:true,sessionSnapshot:true,passRevocation:true},
 system:{selfCreatorRegistration:true,maintenance:false,featureFlags:{dailyChallenge:true,quickPlay:true,qrScanner:true,volunteerHub:true,ttsFallback:true}}
};

export function AdminPage({account}:{account:Account}){
 const [tab,setTab]=React.useState<Tab>('overview'); const [settings,setSettings]=React.useState<any>({}); const [modes,setModes]=React.useState<any[]>([]); const [accounts,setAccounts]=React.useState<any[]>([]); const [sessions,setSessions]=React.useState<any[]>([]); const [passes,setPasses]=React.useState<any[]>([]); const [media,setMedia]=React.useState<any[]>([]); const [support,setSupport]=React.useState<any[]>([]); const [volunteerMedia,setVolunteerMedia]=React.useState<any[]>([]); const [notice,setNotice]=React.useState(''); const [loading,setLoading]=React.useState(true);
 const refresh=React.useCallback(async()=>{setLoading(true);const results=await Promise.allSettled([api.adminSettings(),api.adminModes(),api.adminAccounts(),api.adminSessions(),api.adminPasses(),api.adminMedia(),api.adminSupport(),api.adminVolunteerMedia()]);if(results[0].status==='fulfilled')setSettings(results[0].value.settings||{});if(results[1].status==='fulfilled')setModes(results[1].value.modes||[]);if(results[2].status==='fulfilled')setAccounts(results[2].value.accounts||[]);if(results[3].status==='fulfilled')setSessions(results[3].value.sessions||[]);if(results[4].status==='fulfilled')setPasses(results[4].value.passes||[]);if(results[5].status==='fulfilled')setMedia(results[5].value.items||[]);if(results[6].status==='fulfilled')setSupport(results[6].value.requests||[]);if(results[7].status==='fulfilled')setVolunteerMedia(results[7].value.items||[]);setLoading(false)},[]);
 React.useEffect(()=>{refresh()},[refresh]);
 const save=async(key:string,value:any)=>{try{await api.saveAdminSetting(key,value);setSettings((s:any)=>({...s,[key]:value}));setNotice(`Đã lưu ${key}.`)}catch(e:any){setNotice(e.message)}};
 return <main className="admin-shell-pro"><aside className="admin-sidebar"><div className="admin-logo"><img src="/brand/sky-first-logo.png"/><div><strong>Admin Console</strong><small>{account.displayName}</small></div></div><div className="admin-nav-scroll">{tabs.map(([id,label,icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{icon}<span>{label}</span></button>)}</div><div className="admin-side-note"><ShieldCheck/><div><b>Full Control</b><span>Không góc khuất</span></div></div></aside><section className="admin-main-pro">{notice&&<div className="admin-toast" onClick={()=>setNotice('')}>{notice}</div>}{loading?<div className="admin-loading">Đang đồng bộ D1 / R2 / cấu hình…</div>:<AdminContent tab={tab} settings={settings} modes={modes} accounts={accounts} sessions={sessions} passes={passes} media={media} support={support} volunteerMedia={volunteerMedia} save={save} refresh={refresh} notice={setNotice}/>}</section></main>
}

function Head({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc:string;action?:React.ReactNode}){return <div className="admin-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function AdminContent(p:any){switch(p.tab){case'overview':return <Overview {...p}/>;case'website':return <Website settings={p.settings} save={p.save}/>;case'navigation':return <ConfigEditor keyName="navigation" title="Menu & Footer" icon={<Menu/>} value={p.settings.navigation||defaults.navigation} save={p.save}/>;case'join':return <JoinAdmin value={p.settings.join||defaults.join} save={p.save}/>;case'volunteer':return <VolunteerAdmin value={p.settings.volunteer||defaults.volunteer} media={p.media} support={p.support} volunteerMedia={p.volunteerMedia} save={p.save} refresh={p.refresh} notice={p.notice}/>;case'pages':return <PagesAdmin settings={p.settings} save={p.save}/>;case'languages':return <LanguagesAdmin settings={p.settings} save={p.save}/>;case'games':return <GamesAdmin modes={p.modes} refresh={p.refresh} notice={p.notice}/>;case'content':return <ContentAdmin/>;case'accounts':return <AccountsAdmin accounts={p.accounts} refresh={p.refresh} notice={p.notice}/>;case'access':return <PassAdmin passes={p.passes}/>;case'sessions':return <SessionsAdmin sessions={p.sessions}/>;case'media':return <MediaAdmin items={p.media} refresh={p.refresh} notice={p.notice}/>;case'support':return <SupportAdmin items={p.support} refresh={p.refresh} notice={p.notice}/>;case'security':return <ConfigEditor keyName="security" title="An toàn & Bảo mật" icon={<LockKeyhole/>} value={p.settings.security||defaults.security} save={p.save}/>;default:return <SystemAdmin settings={p.settings} save={p.save}/>}}

function Overview({settings,modes,accounts,sessions,passes,media,support}:any){const active=sessions.filter((x:any)=>['lobby','active'].includes(x.state)).length;return <><Head eyebrow="SYSTEM CONTROL CENTER" title="Sky First Games — Admin" desc="Một trung tâm điều khiển cho website, nội dung, Creator, TNV, game, D1, R2 và vận hành."/><div className="admin-stat-grid"><Stat label="Game Modes" value={modes.length||builtInModes.length} icon={<Gamepad2/>}/><Stat label="Official Packs" value={seedQuestionSets.length} icon={<BookOpen/>}/><Stat label="Ngôn ngữ" value={builtInLanguages.length} icon={<Globe2/>}/><Stat label="Accounts" value={accounts.length} icon={<Users/>}/><Stat label="Live Rooms" value={active} icon={<Radio/>}/><Stat label="Access Pass" value={passes.length} icon={<KeyRound/>}/><Stat label="R2 Assets" value={media.length} icon={<Image/>}/><Stat label="Support" value={support.length} icon={<LifeBuoy/>}/></div><div className="admin-control-grid">{[['Website & Branding','Homepage, logo, màu sắc, CTA, SEO và trạng thái hiển thị.',<Palette/>],['Navigation & Pages','5 menu chính, mega menu Tổng quan, footer và trang chính sách.',<Menu/>],['Learning Engine','20–30 câu mỗi lượt, review, relearn, retest, 15 ngôn ngữ.',<ListChecks/>],['TNV Hub','Access Pass, host, báo cáo, upload ảnh chờ duyệt.',<Users/>],['Game Registry','40+ Game Mode, trạng thái, version, mechanic và compatibility.',<Gamepad2/>],['Security & Operations','Server scoring, privacy, maintenance, logs và feature flags.',<ShieldCheck/>]].map((x:any)=><article key={x[0]}>{x[2]}<h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="admin-health"><h3>System health</h3><div><span className="ok"><CheckCircle2/>Frontend</span><span className="ok"><CheckCircle2/>D1 binding</span><span className="ok"><CheckCircle2/>R2 binding</span><span className={settings.system?.maintenance?'warn':'ok'}>{settings.system?.maintenance?<XCircle/>:<CheckCircle2/>}{settings.system?.maintenance?'Maintenance':'Public online'}</span></div></div></>}
function Stat({label,value,icon}:{label:string;value:any;icon:React.ReactNode}){return <div className="admin-stat">{icon}<div><strong>{value}</strong><span>{label}</span></div></div>}

function Website({settings,save}:{settings:any;save:(k:string,v:any)=>void}){const [v,setV]=React.useState({...defaults.website,...settings.website});React.useEffect(()=>setV({...defaults.website,...settings.website}),[settings]);return <><Head eyebrow="WEBSITE STUDIO" title="Nhận diện & nội dung cốt lõi" desc="Chỉnh các thành phần thương hiệu và nội dung chính mà không cần sửa source." action={<button className="primary-button" onClick={()=>save('website',v)}><Save/>Lưu</button>}/><div className="admin-form-grid"><Field label="Tên sản phẩm" value={v.brandName} set={(x:string)=>setV({...v,brandName:x})}/><Field label="Slogan" value={v.tagline} set={(x:string)=>setV({...v,tagline:x})}/><Field label="Hero title" value={v.heroTitle} set={(x:string)=>setV({...v,heroTitle:x})}/><Field label="Email hỗ trợ" value={v.contactEmail} set={(x:string)=>setV({...v,contactEmail:x})}/><Field label="Website chính" value={v.mainSiteUrl} set={(x:string)=>setV({...v,mainSiteUrl:x})}/><Field label="Màu chính" value={v.primaryColor} set={(x:string)=>setV({...v,primaryColor:x})} type="color"/><label className="full"><span>Hero subtitle</span><textarea rows={4} value={v.heroSubtitle} onChange={e=>setV({...v,heroSubtitle:e.target.value})}/></label></div><div className="brand-preview"><img src="/brand/sky-first-logo.png"/><div><span>{v.tagline}</span><h2>{v.heroTitle}</h2><p>{v.heroSubtitle}</p></div></div></>}
function Field({label,value,set,type='text'}:{label:string;value:any;set:(x:string)=>void;type?:string}){return <label><span>{label}</span><input type={type} value={value??''} onChange={e=>set(e.target.value)}/></label>}

function ConfigEditor({keyName,title,icon,value,save}:{keyName:string;title:string;icon:React.ReactNode;value:any;save:(k:string,v:any)=>void}){const [text,setText]=React.useState(JSON.stringify(value,null,2));const [err,setErr]=React.useState('');React.useEffect(()=>setText(JSON.stringify(value,null,2)),[value]);return <><Head eyebrow="POWER CONFIG" title={title} desc="Form nhanh phía trên hệ thống; JSON nâng cao dành cho cấu hình chi tiết." action={<button className="primary-button" onClick={()=>{try{save(keyName,JSON.parse(text));setErr('')}catch(e:any){setErr(e.message)}}}><Save/>Lưu</button>}/><div className="panel admin-json"><div><span>{icon}</span><b>Cấu hình nâng cao</b></div><textarea value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/>{err&&<div className="error-box">{err}</div>}</div></>}

function JoinAdmin({value,save}:{value:any;save:(k:string,v:any)=>void}){const [v,setV]=React.useState(value);React.useEffect(()=>setV(value),[value]);const toggles=[['code','Nhập mã'],['cameraQr','Quét QR bằng camera'],['uploadQr','Tải ảnh QR'],['directLink','Direct Link'],['requireName','Bắt buộc tên hiển thị'],['allowLateJoin','Cho phép vào muộn'],['safeNickname','Safe nickname']];return <><Head eyebrow="JOIN & ACCESS SETTINGS" title="Tham gia bằng mã, link hoặc QR" desc="Đồng bộ trải nghiệm mobile/desktop và quyền tham gia." action={<button className="primary-button" onClick={()=>save('join',v)}><Save/>Lưu</button>}/><div className="toggle-grid">{toggles.map(([k,l])=><Toggle key={k} label={l} checked={!!v[k]} set={(x:boolean)=>setV({...v,[k]:x})}/>)}</div><div className="admin-form-grid"><label><span>Độ dài mã</span><input type="number" min="4" max="8" value={v.codeLength||6} onChange={e=>setV({...v,codeLength:+e.target.value})}/></label><label><span>Max players mặc định</span><input type="number" value={v.maxPlayers||60} onChange={e=>setV({...v,maxPlayers:+e.target.value})}/></label><label className="full"><span>Thông báo quyền camera</span><input value={v.cameraMessage||''} onChange={e=>setV({...v,cameraMessage:e.target.value})}/></label></div><div className="join-admin-preview"><b>Mobile preview</b><div><button>Nhập mã</button><button>Quét QR</button><button>Tải ảnh QR</button></div></div></>}
function Toggle({label,checked,set}:{label:string;checked:boolean;set:(x:boolean)=>void}){return <button className={checked?'admin-toggle on':'admin-toggle'} onClick={()=>set(!checked)}><span>{checked?'ON':'OFF'}</span><b>{label}</b></button>}

function VolunteerAdmin({value,media,support,volunteerMedia,save,refresh,notice}:any){const [v,setV]=React.useState(value);React.useEffect(()=>setV(value),[value]);const pending=(volunteerMedia||[]).filter((x:any)=>x.status==='pending').length;const reports=support.filter((x:any)=>x.type==='TNV Report').length;return <><Head eyebrow="TNV HUB CONTROL" title="Tình nguyện viên" desc="Quản lý module TNV, Access Pass, báo cáo và media chờ duyệt." action={<button className="primary-button" onClick={()=>save('volunteer',v)}><Save/>Lưu</button>}/><div className="admin-stat-grid"><Stat label="Ảnh chờ duyệt" value={pending} icon={<Image/>}/><Stat label="Báo cáo TNV" value={reports} icon={<FileText/>}/><Stat label="R2 Assets" value={media.length} icon={<UploadCloud/>}/></div><div className="toggle-grid">{[['enabled','TNV Hub'],['gallery','Khu trưng bày'],['uploadsRequireReview','Ảnh phải duyệt'],['reportEnabled','Báo cáo buổi chơi'],['announcements','Thông báo TNV'],['hostByAccessPass','Host bằng Access Pass']].map(([k,l])=><Toggle key={k} label={l} checked={!!v[k]} set={x=>setV({...v,[k]:x})}/>)}</div><div className="volunteer-review-grid">{(volunteerMedia||[]).map((x:any)=><article key={x.id}><img src={x.media_url}/><div><b>{x.pass_label||'TNV Upload'}</b><small>{x.status} • {x.created_at}</small><div><button onClick={async()=>{await api.updateVolunteerMedia(x.id,{status:'approved'});notice('Đã duyệt ảnh TNV.');refresh()}}>Duyệt</button><button onClick={async()=>{await api.updateVolunteerMedia(x.id,{status:'rejected'});notice('Đã từ chối ảnh TNV.');refresh()}}>Từ chối</button></div></div></article>)}</div></>}

function PagesAdmin({settings,save}:any){const cur=settings.pages||{};const [draft,setDraft]=React.useState(cur);React.useEffect(()=>setDraft(cur),[cur]);const update=(slug:string,patch:any)=>setDraft((d:any)=>({...d,[slug]:{enabled:true,...d[slug],...patch}}));return <><Head eyebrow="CONTENT PAGES" title="Trang thông tin & chính sách" desc="Mỗi trang có nội dung dài, mục lục và có thể bật/tắt khỏi menu Tổng quan." action={<button className="primary-button" onClick={()=>save('pages',draft)}><Save/>Lưu</button>}/><div className="page-manager-grid">{Object.values(infoPages).map(pg=>{const x={enabled:true,...draft[pg.slug]};return <article key={pg.slug}><div><FileText/><span>{pg.sections.length} mục</span></div><h3>{pg.title}</h3><p>{pg.intro}</p><label><input type="checkbox" checked={x.enabled} onChange={e=>update(pg.slug,{enabled:e.target.checked})}/> Hiện trong hệ thống</label><input value={x.menuLabel||pg.title} onChange={e=>update(pg.slug,{menuLabel:e.target.value})}/></article>})}</div></>}

function LanguagesAdmin({settings,save}:any){const base=settings.languages?.items||builtInLanguages;const [items,setItems]=React.useState<any[]>(base);React.useEffect(()=>setItems(settings.languages?.items||builtInLanguages),[settings.languages]);return <><Head eyebrow="LANGUAGE CORE" title="15 ngôn ngữ & adapters" desc="UI language và learning language độc lập. Quản lý trạng thái, RTL/LTR, TTS và chuyên môn." action={<button className="primary-button" onClick={()=>save('languages',{items})}><Save/>Lưu</button>}/><div className="language-admin-grid">{items.map((l,i)=><article key={l.code}><div className="language-admin-title"><span>{l.icon}</span><div><b>{l.nativeName}</b><small>{l.name} • {l.code}</small></div></div><select value={l.status} onChange={e=>{const n=[...items];n[i]={...l,status:e.target.value};setItems(n)}}><option value="active">active</option><option value="beta">beta</option><option value="coming_soon">coming soon</option><option value="disabled">disabled</option></select><small>{l.direction?.toUpperCase()} • TTS {l.tts||'—'} • {(l.specialties||[]).join(' · ')}</small></article>)}</div></>}

function GamesAdmin({modes,refresh,notice}:any){const rows=modes.length?modes:builtInModes;return <><Head eyebrow="GAME MANIFEST REGISTRY" title="40+ Game Modes" desc="Bật/tắt, featured, version và trạng thái từng game mode."/><div className="admin-search-row"><Search/><input placeholder="Tìm game mode…"/></div><div className="game-admin-grid">{rows.map((m:any)=><article key={m.id}><span className="game-mode-icon">{m.icon}</span><div><small>{m.family} • {m.mechanic}</small><h3>{m.name}</h3><p>{m.description}</p><span>{m.status} • v{m.version||'2.0'}</span></div>{modes.length>0&&<button onClick={async()=>{await api.updateMode(m.id,{status:m.status==='active'?'disabled':'active'});notice('Đã cập nhật Game Mode.');refresh()}}><ToggleLeft/>{m.status==='active'?'Tắt':'Bật'}</button>}</article>)}</div></>}

function ContentAdmin(){const questions=seedQuestionSets.reduce((a,s)=>a+s.questions.length,0);return <><Head eyebrow="CONTENT ENGINE" title="Official & Creator Content" desc="Question Set tách khỏi Game Mode; một bộ nội dung có thể chạy trên nhiều trò tương thích."/><div className="admin-stat-grid"><Stat label="Official Packs" value={seedQuestionSets.length} icon={<BookOpen/>}/><Stat label="Seed Questions" value={questions} icon={<ListChecks/>}/><Stat label="Question Types" value={22} icon={<Boxes/>}/><Stat label="Language Worlds" value={15} icon={<Languages/>}/></div><div className="admin-control-grid"><article><Database/><h3>Quality Workflow</h3><p>Draft → Review → Verified → Published → Archived.</p></article><article><Braces/><h3>Version & Snapshot</h3><p>Session giữ nguyên nội dung tại thời điểm bắt đầu.</p></article><article><Gamepad2/><h3>Compatibility Engine</h3><p>Chỉ hiển thị game phù hợp với loại câu hỏi và language adapter.</p></article><article><BookOpen/><h3>Learning Loop</h3><p>20–30 câu → xem lại → học câu sai → kiểm tra lại → tiếp tục/thoát.</p></article></div></>}

function AccountsAdmin({accounts,refresh,notice}:any){return <><Head eyebrow="ACCOUNT & PERMISSIONS" title="Creator / Admin Accounts" desc="Một hệ tài khoản; Admin là quyền bổ sung."/><div className="admin-list">{accounts.map((a:any)=><article key={a.id}><div><b>{a.display_name}</b><span>{a.email}</span><small>{a.is_admin?'ADMIN':'CREATOR'} • {a.status}</small></div><div><button onClick={async()=>{await api.updateAccount(a.id,{isAdmin:!a.is_admin});notice('Đã cập nhật quyền.');refresh()}}>{a.is_admin?'Gỡ Admin':'Cấp Admin'}</button><button onClick={async()=>{await api.updateAccount(a.id,{status:a.status==='active'?'suspended':'active'});notice('Đã cập nhật trạng thái.');refresh()}}>{a.status==='active'?'Tạm khóa':'Mở khóa'}</button></div></article>)}</div></>}
function PassAdmin({passes}:any){return <><Head eyebrow="ACCESS PASS" title="Quyền TNV & Host" desc="Theo dõi Access Pass, hạn dùng và trạng thái thu hồi."/><div className="admin-list">{passes.map((x:any)=><article key={x.id}><div><b>{x.label||'TNV Host'}</b><span>Game: {x.game_title||x.game_id}</span><small>{x.revoked_at?'Đã thu hồi':'Đang hoạt động'} • {x.expires_at||'Không giới hạn ngày'}</small></div><code>{x.token}</code></article>)}{!passes.length&&<Empty text="Chưa có Access Pass."/>}</div></>}
function SessionsAdmin({sessions}:any){return <><Head eyebrow="LIVE OPERATIONS" title="Sessions & Rooms" desc="Theo dõi các phiên chơi đang diễn ra và lịch sử phiên."/><div className="admin-list">{sessions.map((s:any)=><article key={s.id}><div><b>{s.game_title||s.game_id}</b><span>Room {s.room_code}</span><small>{s.state} • {s.created_at}</small></div><span className="status-pill">{s.state}</span></article>)}{!sessions.length&&<Empty text="Chưa có session."/>}</div></>}

function MediaAdmin({items,refresh,notice}:any){const [file,setFile]=React.useState<File|null>(null);return <><Head eyebrow="R2 MEDIA LIBRARY" title="Audio, hình ảnh & assets" desc="Quản lý R2 bucket game, media Creator và ảnh TNV chờ duyệt."/><div className="panel media-admin-uploader"><UploadCloud/><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary-button" disabled={!file} onClick={async()=>{if(!file)return;await api.uploadMedia(file);notice('Đã upload media.');setFile(null);refresh()}}>Upload</button></div><div className="media-admin-grid">{items.map((x:any)=><article key={x.key}>{x.type?.startsWith('image')?<img src={x.url}/>:<div className="media-file-icon"><Image/></div>}<b>{x.key.split('/').pop()}</b><small>{x.type||'asset'} • {Math.round((x.size||0)/1024)} KB</small><div><a href={x.url} target="_blank">Mở</a><button onClick={async()=>{await api.deleteAdminMedia(x.key);notice('Đã xóa media.');refresh()}}><Trash2/></button></div></article>)}</div></>}

function SupportAdmin({items,refresh,notice}:any){return <><Head eyebrow="SUPPORT CENTER" title="Yêu cầu, phản hồi & báo lỗi" desc="Theo dõi ticket từ các trang Hỗ trợ, Gửi yêu cầu, Báo lỗi và báo cáo TNV."/><div className="admin-list support-list">{items.map((x:any)=><article key={x.id}><div><span className="eyebrow">{x.ticket_code} • {x.type}</span><b>{x.name||'Người dùng ẩn danh'}</b><p>{x.message}</p><small>{x.email||'Không có email'} • {x.created_at}</small></div><select value={x.status} onChange={async e=>{await api.updateSupport(x.id,{status:e.target.value});notice('Đã cập nhật ticket.');refresh()}}><option>new</option><option>in_progress</option><option>replied</option><option>completed</option></select></article>)}{!items.length&&<Empty text="Chưa có yêu cầu mới."/>}</div></>}
function SystemAdmin({settings,save}:any){const [v,setV]=React.useState({...defaults.system,...settings.system});React.useEffect(()=>setV({...defaults.system,...settings.system}),[settings.system]);return <><Head eyebrow="SYSTEM CONTROL" title="Cấu hình vận hành" desc="Maintenance, self initialization và feature flags." action={<button className="primary-button" onClick={()=>save('system',v)}><Save/>Lưu</button>}/><div className="toggle-grid"><Toggle label="Cho phép tự khởi tạo Creator" checked={!!v.selfCreatorRegistration} set={x=>setV({...v,selfCreatorRegistration:x})}/><Toggle label="Maintenance mode" checked={!!v.maintenance} set={x=>setV({...v,maintenance:x})}/>{Object.entries(v.featureFlags||{}).map(([k,val])=><Toggle key={k} label={k} checked={!!val} set={x=>setV({...v,featureFlags:{...v.featureFlags,[k]:x}})}/>)}</div><div className="panel admin-export"><Download/><div><b>Backup cấu hình</b><p>Tải snapshot settings hiện tại để lưu trữ nội bộ.</p></div><button onClick={()=>{const blob=new Blob([JSON.stringify(settings,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sky-first-games-settings.json';a.click()}}>Export JSON</button></div></>}
function Empty({text}:{text:string}){return <div className="admin-empty">{text}</div>}
