import React from 'react';
import { Activity, BadgeCheck, Boxes, Braces, Database, FileText, Gamepad2, Globe2, Image, Languages, LayoutDashboard, Megaphone, Palette, Save, Search, Settings, ShieldCheck, SlidersHorizontal, ToggleLeft, UploadCloud, Users, Wrench } from 'lucide-react';
import { api } from '../lib/api';
import { languages as builtInLanguages } from '../data/languages';
import { seedQuestionSets } from '../data/seedContent';
import { gameModes as builtInModes } from '../data/gameModes';
import type { Account } from '../types';

type Tab='overview'|'site'|'navigation'|'homepage'|'pages'|'footer'|'branding'|'seo'|'modes'|'languages'|'content'|'matrix'|'collections'|'accounts'|'sessions'|'media'|'moderation'|'system';
const menu:[Tab,string,React.ReactNode][]=[
 ['overview','Tổng quan',<LayoutDashboard/>],['site','Cấu hình website',<Globe2/>],['navigation','Menu & điều hướng',<FileText/>],['homepage','Trang chủ',<Megaphone/>],['pages','Trang nội dung',<FileText/>],['footer','Footer & cổng SFN',<FileText/>],['branding','Branding',<Palette/>],['seo','SEO & Metadata',<Search/>],['modes','Game Modes',<Gamepad2/>],['languages','Ngôn ngữ',<Languages/>],['content','Nội dung',<Database/>],['matrix','Content Matrix',<Boxes/>],['collections','Collections',<SlidersHorizontal/>],['accounts','Creator Accounts',<Users/>],['sessions','Sessions',<Activity/>],['media','Media / R2',<Image/>],['moderation','Moderation',<ShieldCheck/>],['system','Hệ thống',<Settings/>]
];
const langItems=builtInLanguages.map((l,i)=>({code:l.code,name:l.name,nativeName:l.nativeName,icon:l.icon,status:l.status,direction:l.direction,tts:l.tts,scripts:l.scripts,specialties:l.specialties,sortOrder:i+1}));
const defaults:Record<string,any>={
 site:{brandName:'Sky First Games',shortName:'SFG',tagline:'PLAY • LEARN • LEVEL UP',contactEmail:'hotro.sfn@gmail.com',mainSiteUrl:'https://skyfirst.io.vn',mainSiteLabel:'Website chính — Sky First Network',domain:'game.skyfirst.io.vn'},
 navigation:{items:[{label:'Khám phá',url:'/explore'},{label:'Nhập mã',url:'/join'},{label:'Chơi nhanh',url:'/quick-play'}],creatorLabel:'Creator Studio',showMainSite:true},
 homepage:{heroTitle:'Play. Learn. Level Up.',heroSubtitle:'Nền tảng trò chơi học tập đa ngôn ngữ của Sky First — từ lớp học tới đời sống và nơi làm việc.',announcement:'15 ngôn ngữ • 40+ Game Modes • bài tập thực tế',sections:['hero','featured','language-worlds','real-life','creator']},
 pages:{about:{title:'Giới thiệu',intro:'Sky First Games là nền tảng trò chơi học tập đa ngôn ngữ thuộc hệ sinh thái Sky First Network.',body:'Game-first, scenario-first, không phải Academic Hub phiên bản game.'},privacy:{title:'Quyền riêng tư',intro:'Người chơi/TNV có thể tham gia bằng mã hoặc Access Pass mà không cần tài khoản.',body:'Hệ thống ưu tiên tối thiểu dữ liệu và không yêu cầu email/số điện thoại của người chơi.'}},
 footer:{about:'Sky First Games là nền tảng trò chơi học tập đa ngôn ngữ thuộc hệ sinh thái Sky First Network.',contactEmail:'hotro.sfn@gmail.com',portals:[{name:'Cổng Thành viên',domain:'member.skyfirst.io.vn'},{name:'Cổng Tình nguyện viên',domain:'tnv.skyfirst.io.vn'},{name:'Cổng Thông tin',domain:'ctt.skyfirst.io.vn'},{name:'Cổng Học thuật',domain:'academic.skyfirst.io.vn'},{name:'Website chính',domain:'skyfirst.io.vn'}],copyright:'© 2026 Sky First Games — Bản quyền thuộc Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',ecosystemLine:'Một sản phẩm thuộc hệ sinh thái Sky First Network.'},
 branding:{logoUrl:'/brand/sky-first-logo.png',primary:'#0ea5e9',navy:'#07182f',radius:'24px',motion:true,reduceMotionSupport:true},
 seo:{title:'Sky First Games',description:'Nền tảng trò chơi học tập đa ngôn ngữ thuộc hệ sinh thái Sky First Network.',indexable:true,ogImage:'',robots:'index,follow'},
 languages:{items:langItems,uiLanguages:['vi','en'],defaultUiLanguage:'vi'},
 collections:{items:[{id:'quick','title':'Quick Games <5 min'},{id:'classroom','title':'Classroom Party'},{id:'listening','title':'Listening Lab'},{id:'workplace','title':'Workplace & Real Life'},{id:'chinese','title':'Chinese Special'}]},
 moderation:{safeNickname:true,publicContentReview:true,allowFreeChat:false,allowDm:false,reporting:true,blockedWords:[]},
 system:{maintenance:false,selfCreatorRegistration:true,guestPlay:true,featureFlags:{dailyChallenge:true,quickPlay:true,accessPass:true,assignments:true,oneScreen:true,ttsFallback:true,aiDraft:false},limits:{maxPlayersPerRoom:200,maxUploadMb:30,maxQuestionsPerSet:500}}
};

export function AdminPage({account}:{account:Account}){
 const [tab,setTab]=React.useState<Tab>('overview'),[settings,setSettings]=React.useState<Record<string,any>>(defaults),[modes,setModes]=React.useState<any[]>([]),[accounts,setAccounts]=React.useState<any[]>([]),[notice,setNotice]=React.useState('');
 const refresh=()=>{api.adminSettings().then(r=>setSettings({...defaults,...r.settings})).catch(()=>{});api.adminModes().then(r=>setModes(r.modes)).catch(()=>setModes([]));api.adminAccounts().then(r=>setAccounts(r.accounts)).catch(()=>setAccounts([]))};React.useEffect(refresh,[]);
 const save=async(key:string,value:any)=>{try{await api.saveAdminSetting(key,value);setSettings(s=>({...s,[key]:value}));setNotice(`Đã lưu ${key}.`)}catch(e:any){setNotice(e.message)}};
 return <main className="workspace admin-workspace"><aside className="side-nav admin-side"><div className="workspace-title"><img src="/brand/sky-first-logo.png"/><div><strong>Admin Console</strong><small>Full-control • {account.displayName}</small></div></div>{menu.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{icon}{label}</button>)}</aside><section className="workspace-main">{notice&&<div className="toast-inline" onClick={()=>setNotice('')}>{notice}</div>}
 {tab==='overview'&&<Overview settings={settings} modes={modes} accounts={accounts}/>} 
 {(['site','navigation','homepage','pages','footer','branding','seo','collections','moderation','system'] as Tab[]).includes(tab)&&<JsonEditor title={menu.find(x=>x[0]===tab)?.[1]||tab} subtitle="Power configuration — chỉnh từ Admin Console, không cần sửa source cho nội dung/cấu hình vận hành." value={settings[tab]||defaults[tab]} onSave={v=>save(tab,v)}/>} 
 {tab==='languages'&&<LanguageManager value={settings.languages||defaults.languages} onSave={v=>save('languages',v)}/>} 
 {tab==='modes'&&<ModesManager modes={modes.length?modes:builtInModes} live={!!modes.length} onRefresh={refresh} onNotice={setNotice}/>} 
 {tab==='content'&&<ContentPanel/>}{tab==='matrix'&&<MatrixPanel/>}{tab==='accounts'&&<AccountsManager accounts={accounts} onRefresh={refresh} onNotice={setNotice}/>} {tab==='sessions'&&<SessionsPanel/>}{tab==='media'&&<MediaPanel onNotice={setNotice}/>} 
 </section></main>
}

function Overview({settings,modes,accounts}:{settings:any;modes:any[];accounts:any[]}){return <><div className="workspace-head"><div><span className="eyebrow">SYSTEM CONTROL CENTER</span><h1>Sky First Games — Admin</h1><p>Quản trị website, nội dung, Game Engine, ngôn ngữ, Creator, media, sessions và vận hành toàn hệ thống.</p></div><div className="admin-badge"><ShieldCheck/>Full Control</div></div><div className="stat-grid"><div><span>Game Modes</span><strong>{modes.length||builtInModes.length}</strong></div><div><span>Official Packs</span><strong>{seedQuestionSets.length}</strong></div><div><span>Ngôn ngữ</span><strong>{settings.languages?.items?.length||15}</strong></div><div><span>Creator Accounts</span><strong>{accounts.length}</strong></div></div><div className="admin-map"><div><Wrench/><h3>Website CMS</h3><p>Homepage, menu, footer, branding, SEO, pages, cổng SFN và feature flags.</p></div><div><Gamepad2/><h3>Game Platform</h3><p>40+ Game Modes, compatibility, version, status và cấu hình mechanics.</p></div><div><Database/><h3>Content Engine</h3><p>Official/Creator content, 20+ dạng bài, versioning, scenario và audio.</p></div><div><Globe2/><h3>Language Core</h3><p>15 ngôn ngữ, RTL, TTS, script, framework và special exercises.</p></div><div><Users/><h3>Access & Security</h3><p>Creator accounts, quyền Admin, Access Pass, privacy, moderation.</p></div><div><Activity/><h3>Operations</h3><p>Live sessions, reports, R2 media, maintenance và audit.</p></div></div></>}

function JsonEditor({title,subtitle,value,onSave}:{title:string;subtitle:string;value:any;onSave:(v:any)=>void}){const [text,setText]=React.useState(JSON.stringify(value,null,2)),[err,setErr]=React.useState('');React.useEffect(()=>setText(JSON.stringify(value,null,2)),[value]);return <><div className="workspace-head"><div><span className="eyebrow">CMS CONFIG</span><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button" onClick={()=>{try{onSave(JSON.parse(text));setErr('')}catch(e:any){setErr(e.message)}}}><Save/>Lưu thay đổi</button></div><div className="panel code-editor"><div className="code-editor-head"><Braces/>Cấu hình JSON <span>Power editor</span></div><textarea spellCheck={false} value={text} onChange={e=>setText(e.target.value)}/>{err&&<div className="error-box">JSON không hợp lệ: {err}</div>}</div></>}

function LanguageManager({value,onSave}:{value:any;onSave:(v:any)=>void}){const [draft,setDraft]=React.useState(value);React.useEffect(()=>setDraft(value),[value]);const items=draft.items||[];return <><div className="workspace-head"><div><span className="eyebrow">LANGUAGE MANAGER</span><h1>15 ngôn ngữ & Language Adapter</h1><p>Bật/tắt, TTS, hướng chữ, script và tính năng riêng cho từng ngôn ngữ.</p></div><button className="primary-button" onClick={()=>onSave(draft)}><Save/>Lưu</button></div><div className="table-cards language-admin">{items.map((l:any,i:number)=><div className="content-card" key={l.code}><div><span className="eyebrow">{l.code.toUpperCase()} • {l.direction}</span><h3>{l.icon} {l.nativeName}</h3><p>{l.name} • TTS {l.tts||'—'}</p><small>{(l.specialties||[]).join(' • ')}</small></div><div className="card-actions"><select value={l.status} onChange={e=>{const next=[...items];next[i]={...l,status:e.target.value};setDraft({...draft,items:next})}}><option>active</option><option>beta</option><option>coming_soon</option><option>disabled</option></select></div></div>)}</div></>}

function ModesManager({modes,live,onRefresh,onNotice}:{modes:any[];live:boolean;onRefresh:()=>void;onNotice:(s:string)=>void}){return <><div className="workspace-head"><div><span className="eyebrow">GAME MANIFEST REGISTRY</span><h1>Game Modes</h1><p>{live?'Đang đọc từ D1.':'Đang preview manifest built-in; migrate D1 để điều khiển trạng thái thật.'}</p></div></div><div className="table-cards">{modes.map(m=><div className="content-card" key={m.id}><div><span className="eyebrow">{m.family} • v{m.version||'2.0'} • {m.mechanic}</span><h3>{m.icon} {m.name}</h3><p>{m.description}</p><small>{m.status} • {m.min_players??m.minPlayers}–{m.max_players??m.maxPlayers} players</small></div><div className="card-actions">{live&&<button onClick={async()=>{await api.updateMode(m.id,{status:m.status==='active'?'disabled':'active'});onNotice('Đã cập nhật Game Mode.');onRefresh()}}><ToggleLeft/>{m.status==='active'?'Tắt':'Bật'}</button>}</div></div>)}</div></>}

function ContentPanel(){return <><div className="workspace-head"><div><span className="eyebrow">CONTENT PLATFORM</span><h1>Nội dung toàn hệ thống</h1><p>Official Content từ Starter tới Professional, trường học, đời sống, workplace, travel, community và technology.</p></div></div><div className="admin-map"><div><BadgeCheck/><h3>Official Bank</h3><p>{seedQuestionSets.length} pack seed • {seedQuestionSets.reduce((a,s)=>a+s.questions.length,0)} câu mẫu đa dạng.</p></div><div><FileText/><h3>Creator Content</h3><p>Private/link/password/public, version theo lần lưu.</p></div><div><ShieldCheck/><h3>Quality Workflow</h3><p>Draft → Review → Verified → Published → Archived.</p></div><div><Database/><h3>Scenario Content</h3><p>School, work, customer service, volunteer, travel và professional.</p></div></div></>}

function MatrixPanel(){const rows=builtInLanguages.map(l=>{const ss=seedQuestionSets.filter(s=>s.language===l.code);return {l,packs:ss.length,questions:ss.reduce((a,s)=>a+s.questions.length,0),contexts:new Set(ss.map(s=>s.context)).size}});return <><div className="workspace-head"><div><span className="eyebrow">CONTENT MATRIX</span><h1>Độ phủ nội dung</h1><p>Language × context × level × skill để phát hiện khu vực còn mỏng.</p></div></div><div className="matrix-table"><div className="matrix-row head"><b>Ngôn ngữ</b><b>Packs</b><b>Câu hỏi</b><b>Contexts</b><b>Coverage</b></div>{rows.map(r=><div className="matrix-row" key={r.l.code}><span>{r.l.icon} {r.l.nativeName}</span><b>{r.packs}</b><b>{r.questions}</b><b>{r.contexts}</b><span className="coverage"><i style={{width:`${Math.min(100,r.questions/24*100)}%`}}/></span></div>)}</div></>}

function AccountsManager({accounts,onRefresh,onNotice}:{accounts:any[];onRefresh:()=>void;onNotice:(s:string)=>void}){return <><div className="workspace-head"><div><span className="eyebrow">ACCESS CONTROL</span><h1>Creator Accounts</h1><p>Creator tự khởi tạo tài khoản; Admin permission được cấp riêng tại đây.</p></div></div><div className="table-cards">{accounts.map(a=><div className="content-card" key={a.id}><div><span className="eyebrow">{a.is_admin?'ADMIN':'CREATOR'} • {a.status}</span><h3>{a.display_name}</h3><p>{a.email}</p></div><div className="card-actions"><button onClick={async()=>{await api.updateAccount(a.id,{isAdmin:!a.is_admin});onNotice('Đã cập nhật quyền.');onRefresh()}}>{a.is_admin?'Gỡ Admin':'Cấp Admin'}</button><button className={a.status==='active'?'danger-button':''} onClick={async()=>{await api.updateAccount(a.id,{status:a.status==='active'?'suspended':'active'});onNotice('Đã cập nhật trạng thái.');onRefresh()}}>{a.status==='active'?'Tạm khóa':'Mở khóa'}</button></div></div>)}</div></>}

function SessionsPanel(){const [items,setItems]=React.useState<any[]>([]);React.useEffect(()=>{api.adminSessions().then(r=>setItems(r.sessions)).catch(()=>{})},[]);return <><div className="workspace-head"><div><span className="eyebrow">LIVE OPERATIONS</span><h1>Sessions</h1><p>Theo dõi room và trạng thái phiên chơi.</p></div></div><div className="table-cards">{items.map(s=><div className="content-card" key={s.id}><div><span className="eyebrow">{s.state}</span><h3>{s.game_title||s.game_id}</h3><p>Room {s.room_code} • {s.created_at}</p></div></div>)}{!items.length&&<div className="empty-state">Chưa có session trong D1.</div>}</div></>}

function MediaPanel({onNotice}:{onNotice:(s:string)=>void}){const [file,setFile]=React.useState<File|null>(null),[url,setUrl]=React.useState('');return <><div className="workspace-head"><div><span className="eyebrow">R2 MEDIA LIBRARY</span><h1>Audio, hình ảnh & game assets</h1><p>R2 bucket <b>game</b>. Creator cũng có thể upload media trực tiếp trong Question Editor.</p></div></div><div className="panel media-upload"><UploadCloud/><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary-button" disabled={!file} onClick={async()=>{if(!file)return;try{const r=await api.uploadMedia(file);setUrl(r.url);onNotice('Đã upload lên R2.')}catch(e:any){onNotice(e.message)}}}>Upload</button>{url&&<code>{url}</code>}</div></>}
