import React from 'react';
import { Activity, BadgeCheck, Braces, Database, FileText, Gamepad2, Globe2, Image, Languages, LayoutDashboard, Megaphone, Palette, Save, Search, Settings, ShieldCheck, ToggleLeft, UploadCloud, Users } from 'lucide-react';
import { api } from '../lib/api';
import type { Account } from '../types';

type AdminTab='overview'|'site'|'navigation'|'homepage'|'pages'|'footer'|'branding'|'seo'|'modes'|'languages'|'content'|'accounts'|'sessions'|'media'|'system';
const menu:[AdminTab,string,React.ReactNode][]=[
 ['overview','Tổng quan',<LayoutDashboard/>],['site','Cấu hình website',<Globe2/>],['navigation','Menu & điều hướng',<FileText/>],['homepage','Trang chủ',<Megaphone/>],['pages','Trang nội dung',<FileText/>],['footer','Footer',<FileText/>],['branding','Branding',<Palette/>],['seo','SEO & Metadata',<Search/>],['modes','Game Modes',<Gamepad2/>],['languages','Ngôn ngữ',<Languages/>],['content','Nội dung',<Database/>],['accounts','Creator Accounts',<Users/>],['sessions','Sessions',<Activity/>],['media','Media / R2',<Image/>],['system','Hệ thống',<Settings/>]
];

const defaults:Record<string,any>={
 site:{brandName:'Sky First Games',shortName:'SFG',tagline:'Play. Learn. Level Up.',contactEmail:'games@skyfirst.io.vn',mainSiteUrl:'https://skyfirst.io.vn',mainSiteLabel:'Website chính — Sky First Network'},
 navigation:{items:[{label:'Khám phá',url:'/explore'},{label:'Nhập mã',url:'/join'},{label:'Chơi nhanh',url:'/quick-play'}],creatorLabel:'Creator'},
 pages:{about:{title:'Giới thiệu',intro:'Sky First Games là một sản phẩm độc lập trong hệ sinh thái Sky First Network.',body:'Thiết kế đa ngôn ngữ, game-first, không phải cổng học liệu.'},privacy:{title:'Quyền riêng tư',intro:'Người chơi có thể tham gia mà không cần tài khoản.',body:'Sky First Games áp dụng nguyên tắc tối thiểu dữ liệu.'}},
 homepage:{heroTitle:'Chơi để học. Học để đi xa hơn.',heroSubtitle:'Hệ sinh thái trò chơi học tập đa ngôn ngữ của Sky First.',announcement:'Sky First Games đang mở kho game đa ngôn ngữ.',sections:['featured','languages','creator']},
 footer:{about:'Sky First Games là sản phẩm trò chơi học tập thuộc hệ sinh thái Sky First Network.',columns:['Games','Hệ thống','Ngôn ngữ'],showMainSite:true},
 branding:{logoUrl:'/brand/sky-first-network-web.png',primary:'#0ea5e9',navy:'#07182f',radius:'22px'},
 seo:{title:'Sky First Games',description:'Hệ sinh thái trò chơi học tập đa ngôn ngữ của Sky First.',indexable:true},
 languages:{items:[{code:'en',status:'active'},{code:'zh',status:'active'},{code:'ja',status:'beta'},{code:'ko',status:'beta'},{code:'fr',status:'coming_soon'}]},
 system:{maintenance:false,registration:false,guestPlay:true,featureFlags:{dailyChallenge:true,quickPlay:true,accessPass:true,aiDraft:false}}
};

export function AdminPage({account}:{account:Account}){
 const [tab,setTab]=React.useState<AdminTab>('overview');const [settings,setSettings]=React.useState<Record<string,any>>(defaults);const [modes,setModes]=React.useState<any[]>([]);const [accounts,setAccounts]=React.useState<any[]>([]);const [notice,setNotice]=React.useState('');
 const refresh=()=>{api.adminSettings().then(r=>setSettings({...defaults,...r.settings})).catch(()=>{});api.adminModes().then(r=>setModes(r.modes)).catch(()=>{});api.adminAccounts().then(r=>setAccounts(r.accounts)).catch(()=>{})};React.useEffect(refresh,[]);
 const saveSetting=async(key:string,value:any)=>{try{await api.saveAdminSetting(key,value);setSettings(s=>({...s,[key]:value}));setNotice(`Đã lưu ${key}.`)}catch(e:any){setNotice(e.message)}};
 return <main className="workspace admin-workspace"><aside className="side-nav admin-side"><div className="workspace-title"><span>🛡️</span><div><strong>Admin Console</strong><small>Không góc khuất</small></div></div>{menu.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{icon}{label}</button>)}</aside><section className="workspace-main">{notice&&<div className="toast-inline" onClick={()=>setNotice('')}>{notice}</div>}
 {tab==='overview'&&<AdminOverview settings={settings} modes={modes} accounts={accounts}/>} 
 {['site','navigation','homepage','pages','footer','branding','seo','languages','system'].includes(tab)&&<JsonEditor title={menu.find(x=>x[0]===tab)?.[1]||tab} subtitle="Toàn bộ cấu hình này được lưu trong D1 và có thể chỉnh từ Admin Console." value={settings[tab]||defaults[tab]} onSave={v=>saveSetting(tab,v)}/>}
 {tab==='modes'&&<ModesManager modes={modes} onRefresh={refresh} onNotice={setNotice}/>} 
 {tab==='content'&&<ContentManager/>}
 {tab==='accounts'&&<AccountsManager accounts={accounts} onRefresh={refresh} onNotice={setNotice}/>} 
 {tab==='sessions'&&<SessionsPanel/>}
 {tab==='media'&&<MediaPanel onNotice={setNotice}/>} 
 </section></main>
}

function AdminOverview({settings,modes,accounts}:{settings:any,modes:any[],accounts:any[]}){return <><div className="workspace-head"><div><span className="eyebrow">SYSTEM CONTROL CENTER</span><h1>Sky First Games — Admin</h1><p>Quản trị toàn bộ website, nội dung, Game Engine, tài khoản, media và cài đặt vận hành.</p></div><div className="admin-badge"><ShieldCheck/>Full Control</div></div><div className="stat-grid"><div><span>Game Modes</span><strong>{modes.length||40}</strong></div><div><span>Creator Accounts</span><strong>{accounts.length}</strong></div><div><span>Ngôn ngữ</span><strong>{settings.languages?.items?.length||0}</strong></div><div><span>Maintenance</span><strong>{settings.system?.maintenance?'ON':'OFF'}</strong></div></div><div className="admin-map"><div><BadgeCheck/><h3>Website & CMS</h3><p>Homepage, navigation, footer, branding, SEO, thông báo và feature flags.</p></div><div><Gamepad2/><h3>Game Platform</h3><p>Game Modes, compatibility, trạng thái, version và cơ chế bật/tắt.</p></div><div><Database/><h3>Content Engine</h3><p>Question Sets, official content, moderation, languages và collections.</p></div><div><Users/><h3>Access & Operations</h3><p>Creator accounts, Access Pass, sessions, media và nhật ký hệ thống.</p></div></div></>}

function JsonEditor({title,subtitle,value,onSave}:{title:string,subtitle:string,value:any,onSave:(v:any)=>void}){const [text,setText]=React.useState(JSON.stringify(value,null,2));const [err,setErr]=React.useState('');React.useEffect(()=>setText(JSON.stringify(value,null,2)),[value]);const save=()=>{try{const v=JSON.parse(text);setErr('');onSave(v)}catch(e:any){setErr(`JSON không hợp lệ: ${e.message}`)}};return <><div className="workspace-head"><div><span className="eyebrow">CMS CONFIG</span><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button" onClick={save}><Save/>Lưu thay đổi</button></div><div className="panel code-editor"><div className="code-editor-head"><Braces/>Cấu hình JSON <span>Power editor — chỉnh không cần sửa source</span></div><textarea spellCheck={false} value={text} onChange={e=>setText(e.target.value)}/>{err&&<div className="error-box">{err}</div>}</div></>}

function ModesManager({modes,onRefresh,onNotice}:{modes:any[],onRefresh:()=>void,onNotice:(s:string)=>void}){const list=modes.length?modes:[];return <><div className="workspace-head"><div><span className="eyebrow">GAME MANIFEST REGISTRY</span><h1>Game Modes</h1><p>Bật/tắt mode, thay tên, version, mô tả và metadata mà không đóng toàn website.</p></div></div><div className="table-cards">{list.map(m=><div className="content-card" key={m.id}><div><span className="eyebrow">{m.family} • v{m.version||'1.0'}</span><h3>{m.icon} {m.name}</h3><p>{m.description}</p><small>{m.status} • {m.mechanic}</small></div><div className="card-actions"><button onClick={async()=>{await api.updateMode(m.id,{status:m.status==='active'?'disabled':'active'});onNotice('Đã cập nhật trạng thái Game Mode.');onRefresh()}}><ToggleLeft/>{m.status==='active'?'Tắt':'Bật'}</button></div></div>)}{!list.length&&<div className="empty-state">Chạy migration D1 để nạp 40 Game Modes vào Admin.</div>}</div></>}

function ContentManager(){return <><div className="workspace-head"><div><span className="eyebrow">CONTENT PLATFORM</span><h1>Nội dung toàn hệ thống</h1><p>Official Question Bank, Creator Content, challenge, moderation và version history được quản lý trong D1.</p></div></div><div className="admin-map"><div><Database/><h3>Official Bank</h3><p>Nội dung chính thức dùng cho Quick Play, Featured và Daily Challenge.</p></div><div><FileText/><h3>Creator Content</h3><p>Bộ câu hỏi riêng của tài khoản Creator, theo visibility và version.</p></div><div><BadgeCheck/><h3>Review & Publish</h3><p>Draft → Review → Verified → Published → Archived.</p></div><div><Globe2/><h3>Collections</h3><p>Nhóm game/nội dung theo chủ đề, ngôn ngữ, mùa và hoạt động.</p></div></div><div className="panel"><p>API nền đã có bảng <code>question_sets</code>, <code>questions</code>, <code>games</code>, <code>sessions</code> và <code>results</code>. Creator Studio là nơi chỉnh nội dung chi tiết; Admin Console chịu trách nhiệm kiểm soát toàn cục.</p></div></>}

function AccountsManager({accounts,onRefresh,onNotice}:{accounts:any[],onRefresh:()=>void,onNotice:(s:string)=>void}){const [email,setEmail]=React.useState('');const [name,setName]=React.useState('');const [password,setPassword]=React.useState('');const create=async()=>{try{await api.createAccount({email,displayName:name,password,isAdmin:false});setEmail('');setName('');setPassword('');onNotice('Đã tạo Creator Account.');onRefresh()}catch(e:any){onNotice(e.message)}};return <><div className="workspace-head"><div><span className="eyebrow">ACCESS CONTROL</span><h1>Creator Accounts</h1><p>Người chơi/TNV không cần account; account chỉ dành cho người tạo và quản trị.</p></div></div><div className="panel inline-create"><input placeholder="Tên hiển thị" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Mật khẩu tạm" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary-button" onClick={create}>Tạo tài khoản</button></div><div className="table-cards">{accounts.map(a=><div className="content-card" key={a.id}><div><span className="eyebrow">{a.is_admin?'ADMIN':'CREATOR'} • {a.status}</span><h3>{a.display_name}</h3><p>{a.email}</p></div><div className="card-actions"><button onClick={async()=>{await api.updateAccount(a.id,{status:a.status==='active'?'suspended':'active'});onRefresh()}}>{a.status==='active'?'Tạm khóa':'Kích hoạt'}</button></div></div>)}</div></>}
function SessionsPanel(){
 const [sessions,setSessions]=React.useState<any[]>([]);const [err,setErr]=React.useState('');
 React.useEffect(()=>{api.adminSessions().then(r=>setSessions(r.sessions)).catch(e=>setErr(e.message))},[]);
 return <><div className="workspace-head"><div><span className="eyebrow">LIVE OPERATIONS</span><h1>Sessions & Rooms</h1><p>Theo dõi phòng đang chạy, lịch sử phiên và trạng thái host.</p></div></div>{err&&<div className="error-box">{err}</div>}<div className="table-cards">{sessions.map(s=><div className="content-card" key={s.id}><div><span className="eyebrow">{s.state} • {s.mode_id}</span><h3>{s.game_title}</h3><p>Room: <b>{s.room_code}</b> • Bắt đầu: {s.started_at||'—'}</p></div></div>)}{!sessions.length&&!err&&<div className="panel empty-state">Chưa có session nào.</div>}</div></>
}
function MediaPanel({onNotice}:{onNotice:(s:string)=>void}){const [url,setUrl]=React.useState('');return <><div className="workspace-head"><div><span className="eyebrow">R2 MEDIA</span><h1>Media Library</h1><p>Upload hình/audio/game assets trực tiếp vào R2 bucket <code>game</code>.</p></div></div><div className="panel upload-panel"><UploadCloud size={42}/><h3>Upload media</h3><input type="file" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await api.uploadMedia(f);setUrl(r.url);onNotice('Upload R2 thành công.')}catch(err:any){onNotice(err.message)}}}/>{url&&<p>URL: <code>{url}</code></p>}</div></>}
