import React from 'react';
import { Copy, Gamepad2, KeyRound, LayoutDashboard, Plus, Save, Send, Trash2, WandSparkles } from 'lucide-react';
import { api } from '../lib/api';
import { gameModes } from '../data/gameModes';
import { seedQuestionSets } from '../data/seedContent';
import type { Account, Question, QuestionSet } from '../types';

function uid(){return crypto.randomUUID()}
const emptyQuestion=():Question=>({id:uid(),type:'multiple_choice',prompt:'',options:['','','',''],answers:['']});
export function CreatorPage({account}:{account:Account}){
 const [tab,setTab]=React.useState<'overview'|'sets'|'games'|'passes'>('overview'); const [sets,setSets]=React.useState<QuestionSet[]>([]);const [games,setGames]=React.useState<any[]>([]);const [passes,setPasses]=React.useState<any[]>([]);const [editing,setEditing]=React.useState<QuestionSet|null>(null);const [message,setMessage]=React.useState('');
 const refresh=()=>{api.creatorSets().then(r=>setSets(r.sets)).catch(()=>setSets([]));api.listGames().then(r=>setGames(r.games)).catch(()=>{});api.listPasses().then(r=>setPasses(r.passes)).catch(()=>{})};React.useEffect(refresh,[]);
 const newSet=()=>setEditing({id:'',title:'Bộ câu hỏi mới',language:'en',level:'A1',topic:'Vocabulary',description:'',isOfficial:false,visibility:'private',updatedAt:'',questions:[emptyQuestion()]});
 const save=async()=>{if(!editing)return;try{const r=await api.saveSet(editing);setEditing(r.set);setMessage('Đã lưu bộ câu hỏi.');refresh()}catch(e:any){setMessage(e.message)}};
 const createGame=async(set:QuestionSet)=>{const compatible=gameModes.find(m=>m.status==='active'&&m.supportedQuestionTypes.some(t=>set.questions.some(q=>q.type===t)))||gameModes[0];try{const r=await api.createGame({title:`${compatible.name} — ${set.title}`,modeId:compatible.id,setId:set.id,visibility:'link',config:{shuffle:true,showAnswers:true}});setMessage(`Đã tạo game. Mã: ${r.game.join_code}`);refresh()}catch(e:any){setMessage(e.message)}};
 const createPass=async(game:any)=>{try{const r=await api.createPass({gameId:game.id,label:`TNV — ${game.title}`,permissions:['host','view_results'],expiresAt:null});setMessage(`Access Pass đã tạo: ${location.origin}/host/${r.pass.token}`);refresh()}catch(e:any){setMessage(e.message)}};
 return <main className="workspace"><aside className="side-nav"><div className="workspace-title"><span>🛠️</span><div><strong>Creator Studio</strong><small>{account.displayName}</small></div></div><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard/>Tổng quan</button><button className={tab==='sets'?'active':''} onClick={()=>setTab('sets')}><WandSparkles/>Bộ câu hỏi</button><button className={tab==='games'?'active':''} onClick={()=>setTab('games')}><Gamepad2/>Trò chơi</button><button className={tab==='passes'?'active':''} onClick={()=>setTab('passes')}><KeyRound/>Access Pass</button></aside><section className="workspace-main">{message&&<div className="toast-inline" onClick={()=>setMessage('')}>{message}</div>}
 {tab==='overview'&&<><div className="workspace-head"><div><span className="eyebrow">CREATOR STUDIO</span><h1>Xin chào, {account.displayName}</h1><p>Tạo nội dung một lần, phối với nhiều Game Mode và chia sẻ cho TNV bằng link/PIN.</p></div><button className="primary-button" onClick={()=>{setTab('sets');newSet()}}><Plus/>Tạo bộ câu hỏi</button></div><div className="stat-grid"><div><span>Bộ câu hỏi</span><strong>{sets.length}</strong></div><div><span>Game đã tạo</span><strong>{games.length}</strong></div><div><span>Access Pass</span><strong>{passes.filter(p=>!p.revoked_at).length}</strong></div><div><span>Game Modes</span><strong>{gameModes.length}</strong></div></div><div className="panel"><h3>Nội dung chính thức có sẵn</h3><div className="mini-list">{seedQuestionSets.slice(0,4).map(s=><div key={s.id}><span>{s.language==='en'?'🇬🇧':s.language==='zh'?'🇨🇳':s.language==='ja'?'🇯🇵':'🇰🇷'}</span><div><strong>{s.title}</strong><small>{s.questions.length} câu • Sky First Official</small></div></div>)}</div></div></>}
 {tab==='sets'&&<>{editing?<SetEditor set={editing} onChange={setEditing} onSave={save} onClose={()=>setEditing(null)}/>:<><div className="workspace-head"><div><span className="eyebrow">CONTENT ENGINE</span><h1>Bộ câu hỏi</h1><p>Question Set là nội dung; Game Mode là cách chơi. Hai phần tách biệt.</p></div><button className="primary-button" onClick={newSet}><Plus/>Tạo mới</button></div><div className="table-cards">{sets.map(s=><div className="content-card" key={s.id}><div><span className="eyebrow">{s.language.toUpperCase()} • {s.level}</span><h3>{s.title}</h3><p>{s.description||'Chưa có mô tả'}</p><small>{s.questions?.length||0} câu • {s.visibility}</small></div><div className="card-actions"><button onClick={()=>setEditing(s)}>Sửa</button><button onClick={()=>createGame(s)}>Tạo game</button><button className="danger" onClick={async()=>{if(confirm('Xóa bộ câu hỏi này?')){await api.deleteSet(s.id);refresh()}}}><Trash2/></button></div></div>)}{!sets.length&&<div className="empty-state">Chưa có bộ câu hỏi riêng. Nội dung official vẫn có sẵn cho Quick Play.</div>}</div></>}</>}
 {tab==='games'&&<><div className="workspace-head"><div><span className="eyebrow">GAME INSTANCE</span><h1>Trò chơi đã tạo</h1><p>Mỗi game liên kết một Question Set với một Game Mode và cấu hình truy cập riêng.</p></div></div><div className="table-cards">{games.map(g=><div className="content-card" key={g.id}><div><span className="eyebrow">{g.mode_id}</span><h3>{g.title}</h3><p>Mã tham gia: <b>{g.join_code}</b> • {g.visibility}</p></div><div className="card-actions"><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/join?code=${g.join_code}`)}><Copy/>Copy link</button><button onClick={()=>createPass(g)}><Send/>Tạo pass TNV</button></div></div>)}{!games.length&&<div className="empty-state">Chưa có game. Mở một bộ câu hỏi và chọn “Tạo game”.</div>}</div></>}
 {tab==='passes'&&<><div className="workspace-head"><div><span className="eyebrow">HOST ACCESS</span><h1>Access Pass</h1><p>Cấp quyền host tạm thời cho TNV mà không cần tạo tài khoản.</p></div></div><div className="table-cards">{passes.map(p=><div className="content-card" key={p.id}><div><span className="eyebrow">{p.revoked_at?'ĐÃ THU HỒI':'ĐANG HOẠT ĐỘNG'}</span><h3>{p.label}</h3><p>Host link: <code>{location.origin}/host/{p.token}</code></p><small>{p.permissions_json}</small></div><div className="card-actions">{!p.revoked_at&&<button onClick={()=>navigator.clipboard.writeText(`${location.origin}/host/${p.token}`)}><Copy/>Copy host link</button>}{!p.revoked_at&&<button className="danger-button" onClick={async()=>{await api.revokePass(p.id);refresh()}}>Thu hồi</button>}</div></div>)}{!passes.length&&<div className="empty-state">Chưa có Access Pass.</div>}</div></>}
 </section></main>;
}

function SetEditor({set,onChange,onSave,onClose}:{set:QuestionSet,onChange:(s:QuestionSet)=>void,onSave:()=>void,onClose:()=>void}){
 const patch=(p:Partial<QuestionSet>)=>onChange({...set,...p}); const updateQ=(i:number,p:Partial<Question>)=>patch({questions:set.questions.map((q,idx)=>idx===i?{...q,...p}:q)});
 return <><div className="workspace-head"><div><span className="eyebrow">QUESTION EDITOR</span><h1>{set.title}</h1></div><div className="button-row"><button className="secondary-button" onClick={onClose}>Đóng</button><button className="primary-button" onClick={onSave}><Save/>Lưu</button></div></div><div className="panel form-grid"><label>Tiêu đề<input value={set.title} onChange={e=>patch({title:e.target.value})}/></label><label>Ngôn ngữ<select value={set.language} onChange={e=>patch({language:e.target.value})}><option value="en">English</option><option value="zh">中文</option><option value="ja">日本語</option><option value="ko">한국어</option></select></label><label>Cấp độ<input value={set.level} onChange={e=>patch({level:e.target.value})}/></label><label>Chủ đề<input value={set.topic} onChange={e=>patch({topic:e.target.value})}/></label><label className="span2">Mô tả<textarea value={set.description} onChange={e=>patch({description:e.target.value})}/></label><label>Quyền truy cập<select value={set.visibility} onChange={e=>patch({visibility:e.target.value as any})}><option value="private">Private</option><option value="link">Link only</option><option value="password">Password</option><option value="public">Public</option></select></label></div><div className="question-editor-list">{set.questions.map((q,i)=><div className="question-edit-card" key={q.id}><div className="q-head"><strong>Câu {i+1}</strong><select value={q.type} onChange={e=>updateQ(i,{type:e.target.value as any})}><option value="multiple_choice">Multiple choice</option><option value="true_false">True / False</option><option value="typed">Typed answer</option><option value="fill_blank">Fill blank</option><option value="matching">Matching</option><option value="ordering">Ordering</option><option value="sentence_builder">Sentence Builder</option></select><button className="icon-button danger" onClick={()=>patch({questions:set.questions.filter((_,idx)=>idx!==i)})}><Trash2/></button></div><textarea value={q.prompt} onChange={e=>updateQ(i,{prompt:e.target.value})} placeholder="Nội dung câu hỏi"/>{q.options&&<div className="option-edit-grid">{q.options.map((o,oi)=><input key={oi} value={o} onChange={e=>{const opts=[...(q.options||[])];opts[oi]=e.target.value;updateQ(i,{options:opts})}} placeholder={`Đáp án ${oi+1}`}/>)}</div>}<input value={q.answers.join('|')} onChange={e=>updateQ(i,{answers:e.target.value.split('|').map(x=>x.trim())})} placeholder="Đáp án đúng; dùng | nếu có nhiều đáp án chấp nhận"/><input value={q.explanation||''} onChange={e=>updateQ(i,{explanation:e.target.value})} placeholder="Giải thích (không bắt buộc)"/></div>)}<button className="secondary-button full" onClick={()=>patch({questions:[...set.questions,emptyQuestion()]})}><Plus/>Thêm câu hỏi</button></div></>
}
