import React from 'react';
import { Copy, KeyRound, Loader2, Play, ShieldCheck, Users } from 'lucide-react';
import { api } from '../lib/api';
function wsUrl(path:string){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}${path}`}

export function HostPage({token}:{token:string}){
 const [pin,setPin]=React.useState(''),[unlocked,setUnlocked]=React.useState(false),[data,setData]=React.useState<any>(null),[err,setErr]=React.useState(''),[session,setSession]=React.useState<any>(null),[players,setPlayers]=React.useState<any[]>([]),[busy,setBusy]=React.useState(false);
 const unlock=async()=>{setBusy(true);setErr('');try{const d=await api.hostPass(token,pin);setData(d);setUnlocked(true)}catch(e:any){setErr(e.message)}finally{setBusy(false)}};
 React.useEffect(()=>{if(!session?.id)return;let ws:WebSocket|undefined;try{ws=new WebSocket(wsUrl(`/api/live/${session.id}?role=host&pass=${encodeURIComponent(token)}`));ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.players)setPlayers(d.players)}catch{}}}catch{}return()=>ws?.close()},[session?.id,token]);
 if(!unlocked)return <main className="auth-page"><section className="auth-card"><div className="host-badge"><ShieldCheck/>TNV HOST ACCESS</div><h1>Mở Access Pass</h1><p>Nhập PIN Host do Creator gửi kèm link. TNV không cần tài khoản.</p><label><span><KeyRound/> PIN</span><input inputMode="numeric" maxLength={8} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="4–8 chữ số"/></label>{err&&<div className="error-box">{err}</div>}<button className="primary-button big full" disabled={!pin||busy} onClick={unlock}>{busy?<Loader2 className="spin"/>:<KeyRound/>}{busy?'Đang kiểm tra…':'Mở quyền Host'}</button></section></main>;
 const joinUrl=`${location.origin}/join?code=${data.game.join_code}`;
 return <main className="host-page"><section className="host-card"><div className="host-badge"><ShieldCheck/>TNV HOST ACCESS</div><h1>{data.game.title}</h1><p>{data.set.title} • {data.set.questions.length} câu • Game Mode: {data.game.mode_id}</p><div className="host-code"><span>MÃ THAM GIA</span><strong>{data.game.join_code}</strong><button onClick={()=>navigator.clipboard.writeText(joinUrl)}><Copy/>Copy link</button></div>{session?<><div className="session-live"><span>● SESSION ACTIVE</span><strong>{session.room_code}</strong><p><Users/> {players.length} người đang kết nối realtime.</p></div><div className="player-roster">{players.map(p=><span key={p.id}>{p.nickname}</span>)}{!players.length&&<small>Đang chờ học viên vào phòng… Nếu Pages chưa có Durable Object, session vẫn chạy ở chế độ cơ bản.</small>}</div></>:<button className="primary-button big full" onClick={async()=>setSession((await api.startHostSession(token,pin)).session)}><Play/>Bắt đầu phiên</button>}<div className="host-note"><KeyRound/>Access Pass chỉ cấp quyền cho game này; Creator có thể thu hồi bất kỳ lúc nào.</div></section></main>
}
