import React from 'react';
import { ArrowLeft, LockKeyhole, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { api, authToken } from '../lib/api';
import { navigate } from '../lib/router';
import type { Account } from '../types';

export function LoginPage({onAuth}:{onAuth:(account:Account)=>void}){
  const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [displayName,setDisplayName]=React.useState(''); const [setupKey,setSetupKey]=React.useState('');
  const [bootstrap,setBootstrap]=React.useState(false); const [checking,setChecking]=React.useState(true); const [busy,setBusy]=React.useState(false); const [msg,setMsg]=React.useState('');
  React.useEffect(()=>{api.authStatus().then(r=>setBootstrap(!r.initialized)).catch(()=>setBootstrap(false)).finally(()=>setChecking(false))},[]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMsg('');try{const r=bootstrap?await api.bootstrap(setupKey,email.trim(),password,displayName.trim()):await api.login(email.trim(),password);authToken.set(r.token);onAuth(r.account);navigate(r.account.isAdmin?'/admin':'/creator')}catch(e:any){setMsg(e.message||'Không thể đăng nhập.')}finally{setBusy(false)}};
  return <main className="auth-page auth-v2"><div className="auth-backdrop"><span/><span/><span/></div><button className="auth-back" onClick={()=>navigate('/')}><ArrowLeft/>Trang chủ</button><section className="auth-card auth-card-v2"><div className="auth-brand"><img src="/brand/sky-first-logo.png" alt="Sky First"/><div><strong>Sky First Games</strong><small>Creator & Admin</small></div></div><span className="eyebrow">{bootstrap?'FIRST SYSTEM SETUP':'SECURE ACCESS'}</span><h1>{checking?'Đang kiểm tra hệ thống…':bootstrap?'Khởi tạo Admin đầu tiên':'Đăng nhập'}</h1><p>{bootstrap?'Chỉ dùng khi hệ thống chưa có tài khoản nào. Sau lần đầu, trang này trở về chế độ đăng nhập.':'Sử dụng tài khoản Sky First Games để truy cập Creator Studio. Tài khoản được cấp quyền Admin sẽ được chuyển tới Admin Console.'}</p>{!checking&&<form onSubmit={submit}>{bootstrap&&<label><span>Tên hiển thị</span><input required value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Tên hiển thị"/></label>}<label><span><Mail/>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label><span><LockKeyhole/>Mật khẩu</span><input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Tối thiểu 8 ký tự"/></label>{bootstrap&&<label><span><ShieldCheck/>ADMIN_SETUP_KEY</span><input type="password" required value={setupKey} onChange={e=>setSetupKey(e.target.value)} placeholder="Setup key trong Worker secret"/></label>}{msg&&<div className="error-box">{msg}</div>}<button className="primary-button full big" disabled={busy}>{busy?'Đang xử lý…':bootstrap?'Khởi tạo Admin':'Đăng nhập'}</button></form>}<div className="auth-note"><Sparkles/><span>Người học và TNV không cần tài khoản để tham gia game. Creator có thể tự khởi tạo qua đường dẫn khởi tạo riêng khi được phép.</span></div></section></main>
}
