import React from 'react';
import { ArrowLeft, LockKeyhole, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { api, authToken } from '../lib/api';
import { navigate } from '../lib/router';
import type { Account } from '../types';

export function LoginPage({onAuth}:{onAuth:(account:Account)=>void}){
  const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [displayName,setDisplayName]=React.useState(''); const [setupKey,setSetupKey]=React.useState('');
  const [bootstrap,setBootstrap]=React.useState(false); const [checking,setChecking]=React.useState(true); const [busy,setBusy]=React.useState(false); const [msg,setMsg]=React.useState('');
  React.useEffect(()=>{api.authStatus().then(r=>setBootstrap(!r.initialized)).catch(()=>setBootstrap(false)).finally(()=>setChecking(false))},[]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMsg('');try{const r=bootstrap?await api.bootstrap(setupKey,email.trim(),password,displayName.trim()):await api.login(email.trim(),password);authToken.set(r.token);onAuth(r.account);navigate(r.account.isAdmin?'/admin':'/creator')}catch(e:any){setMsg(e.message||'Unable to sign in.')}finally{setBusy(false)}};
  return <main className="auth-page auth-v2"><div className="auth-backdrop"><span/><span/><span/></div><button className="auth-back" onClick={()=>navigate('/')}><ArrowLeft/>Home</button><section className="auth-card auth-card-v2"><div className="auth-brand"><img src="/brand/sky-first-logo.png" alt="Sky First"/><div><strong>Sky First Games</strong><small>Creator & Admin</small></div></div><span className="eyebrow">{bootstrap?'FIRST SYSTEM SETUP':'SECURE ACCESS'}</span><h1>{checking?'Checking system…':bootstrap?'Initialize the first Admin':'Sign in'}</h1><p>{bootstrap?'Use this once when the database has no accounts. After setup, this page becomes the normal sign-in screen.':'Use your Sky First Games account to access Creator Studio. Accounts with Admin permission are routed to Admin Console.'}</p>{!checking&&<form onSubmit={submit}>{bootstrap&&<label><span>Display name</span><input required value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name"/></label>}<label><span><Mail/>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label><span><LockKeyhole/>Password</span><input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label>{bootstrap&&<label><span><ShieldCheck/>ADMIN_SETUP_KEY</span><input type="password" required value={setupKey} onChange={e=>setSetupKey(e.target.value)} placeholder="Worker setup secret"/></label>}{msg&&<div className="error-box">{msg}</div>}<button className="primary-button full big" disabled={busy}>{busy?'Processing…':bootstrap?'Initialize Admin':'Sign in'}</button></form>}<div className="auth-note"><Sparkles/><span>Learners and volunteers do not need accounts to join games. Creator accounts can be self-initialized through the dedicated initialization route when enabled.</span></div></section></main>
}
