import React from 'react';
import { KeyRound, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { api, authToken } from '../lib/api';
import { navigate } from '../lib/router';
import type { Account } from '../types';

export function LoginPage({onAuth}:{onAuth:(a:Account)=>void}){
 const [initialized,setInitialized]=React.useState<boolean|null>(null); const [loading,setLoading]=React.useState(false); const [error,setError]=React.useState('');
 const [email,setEmail]=React.useState('');const [password,setPassword]=React.useState('');const [displayName,setDisplayName]=React.useState('');const [setupKey,setSetupKey]=React.useState('');
 React.useEffect(()=>{api.authStatus().then(x=>setInitialized(x.initialized)).catch(()=>setInitialized(true))},[]);
 const submit=async()=>{setLoading(true);setError('');try{const r=initialized===false?await api.bootstrap(setupKey,email,password,displayName):await api.login(email,password);authToken.set(r.token);onAuth(r.account);navigate(r.account.isAdmin?'/admin':'/creator')}catch(e:any){setError(e.message||'Không thể đăng nhập')}finally{setLoading(false)}};
 return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><span><ShieldCheck/></span><div><strong>Sky First Games</strong><small>Creator & Admin Access</small></div></div><h1>{initialized===false?'Khởi tạo hệ thống':'Đăng nhập Creator'}</h1><p>{initialized===false?'Tạo tài khoản quản trị đầu tiên. Setup key lấy từ biến môi trường ADMIN_SETUP_KEY.':'Khu vực dành cho tài khoản tạo nội dung và quản trị hệ thống.'}</p>{initialized===false&&<label>Tên hiển thị<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Sky First Admin"/></label>}<label>Email<div className="input-icon"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@skyfirst.io.vn"/></div></label><label>Mật khẩu<div className="input-icon"><LockKeyhole/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></div></label>{initialized===false&&<label>Setup key<div className="input-icon"><KeyRound/><input type="password" value={setupKey} onChange={e=>setSetupKey(e.target.value)} placeholder="ADMIN_SETUP_KEY"/></div></label>}{error&&<div className="error-box">{error}</div>}<button className="primary-button big full" onClick={submit} disabled={loading||!email||!password||(initialized===false&&(!displayName||!setupKey))}>{loading?'Đang xử lý…':initialized===false?'Khởi tạo & đăng nhập':'Đăng nhập'}</button><button className="text-button center" onClick={()=>navigate('/')}>← Quay về trang chơi</button></section></main>
}
