import React from 'react';
import { Dices } from 'lucide-react';
import { languages } from '../data/languages';
import { gameModes } from '../data/gameModes';
import { seedQuestionSets } from '../data/seedContent';
import { navigate } from '../lib/router';
export function QuickPlayPage(){
 const [lang,setLang]=React.useState('en'),[minutes,setMinutes]=React.useState('5'),[context,setContext]=React.useState('any');
 const play=()=>{let sets=seedQuestionSets.filter(s=>s.language===lang&&(context==='any'||s.context===context));if(!sets.length)sets=seedQuestionSets.filter(s=>s.language===lang);const set=sets[Math.floor(Math.random()*sets.length)]||seedQuestionSets[0];const compatible=gameModes.filter(m=>m.status==='active'&&(m.languages==='universal'||m.languages.includes(lang))&&m.supportedQuestionTypes.some(t=>set.questions.some(q=>q.type===t))&&m.durationMinutes[0]<=Number(minutes)+5);const mode=compatible[Math.floor(Math.random()*compatible.length)]||gameModes[0];navigate(`/play?mode=${mode.id}&set=${set.id}`)};
 return <main className="page-shell narrow"><div className="page-hero compact"><span className="eyebrow">QUICK PLAY</span><h1>Choose a goal. Let the platform match the game.</h1><p>Question Sets and Game Modes are independent, so the same learning content can become many different experiences.</p></div><div className="panel form-panel"><label>Learning language<select value={lang} onChange={e=>setLang(e.target.value)}>{languages.filter(l=>l.status==='active').map(l=><option value={l.code} key={l.code}>{l.icon} {l.nativeName}</option>)}</select></label><label>Context<select value={context} onChange={e=>setContext(e.target.value)}><option value="any">Any context</option>{['School & Exam','Daily Life','Workplace','School Workplace','Business & Office','Travel','Public Services','Technology','Community & Volunteer','Social & Relationships','Advanced / Professional'].map(x=><option key={x}>{x}</option>)}</select></label><label>Approximate duration<select value={minutes} onChange={e=>setMinutes(e.target.value)}><option value="3">About 3 minutes</option><option value="5">About 5 minutes</option><option value="10">About 10 minutes</option><option value="15">About 15 minutes</option><option value="25">About 25 minutes</option></select></label><button className="primary-button big full" onClick={play}><Dices/>Choose a Game for Me</button></div></main>
}
