import React from 'react';
import { Camera, ClipboardCheck, ImagePlus, KeyRound, Megaphone, PlayCircle, QrCode, ShieldCheck, UploadCloud, Users2 } from 'lucide-react';
import { api } from '../lib/api';
import { navigate } from '../lib/router';
import type { SiteConfig } from '../types';

export function VolunteerPage({config}:{config?:SiteConfig}){
  const [token,setToken]=React.useState(''); const [pin,setPin]=React.useState(''); const [pass,setPass]=React.useState<any>(null); const [msg,setMsg]=React.useState('');
  const [report,setReport]=React.useState(''); const [file,setFile]=React.useState<File|null>(null); const [preview,setPreview]=React.useState(''); const [gallery,setGallery]=React.useState<any[]>([]);
  React.useEffect(()=>{api.publicVolunteerGallery().then(r=>setGallery(r.items||[])).catch(()=>{})},[]);
  const openPass=async()=>{setMsg('');try{const r=await api.hostPass(token.trim(),pin.trim());setPass(r);setMsg('Access Pass hợp lệ. Bạn có thể mở phiên được giao.')}catch(e:any){setMsg(e.message)}};
  const upload=async()=>{if(!file||!token)return;try{const r=await api.volunteerUpload(token,pin,file);setPreview(r.url);setMsg('Ảnh đã tải lên và đang chờ Admin duyệt.')}catch(e:any){setMsg(e.message)}};
  const sendReport=async()=>{if(!report.trim())return;try{await api.volunteerReport({token,pin,report});setReport('');setMsg('Đã gửi báo cáo TNV.')}catch(e:any){setMsg(e.message)}};
  if(config?.volunteerSettings?.enabled===false)return <main className="page-shell narrow"><div className="page-hero compact"><h1>TNV Hub đang tạm tắt</h1><p>Vui lòng quay lại sau hoặc liên hệ hotro.sfn@gmail.com.</p></div></main>;
  return <main className="page-shell volunteer-shell"><div className="page-hero volunteer-hero"><span className="eyebrow">TÌNH NGUYỆN VIÊN</span><h1>TNV Hub</h1><p>Không cần tài khoản riêng. Sử dụng Access Pass hoặc Host PIN được Creator cấp để mở nội dung, tổ chức phiên chơi, gửi báo cáo và tải ảnh hoạt động.</p><div className="hero-proof"><span><ShieldCheck/><b>Access Pass</b> phân quyền tạm thời</span><span><Users2/><b>Host</b> lớp học & hoạt động</span><span><Camera/><b>Media</b> chờ Admin duyệt</span></div></div>
  <section className="tnv-grid"><div className="panel tnv-access"><span className="eyebrow">ACCESS PASS</span><h2>Mở khu TNV được giao</h2><label><span><KeyRound/>Mã/Token Access Pass</span><input value={token} onChange={e=>setToken(e.target.value)} placeholder="Dán token hoặc mã được cấp"/></label><label><span>PIN</span><input inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN nếu có"/></label><button className="primary-button full" onClick={openPass} disabled={!token.trim()}>Xác thực Access Pass</button>{msg&&<div className="toast-inline static">{msg}</div>}</div>
  <div className="tnv-feature-grid"><article><PlayCircle/><h3>Game được giao</h3><p>Mở game theo quyền Creator đã cấp, tạo phiên mới và lấy mã/QR cho học viên.</p></article><article><QrCode/><h3>Host phiên chơi</h3><p>Điều khiển session, bắt đầu, tạm dừng, chuyển round và kết thúc buổi chơi.</p></article><article><ClipboardCheck/><h3>Báo cáo sau buổi</h3><p>Ghi lại số lượng tham gia, tình hình lớp và nội dung cần theo dõi.</p></article><article><Megaphone/><h3>Thông báo TNV</h3><p>Nhận hướng dẫn và thông tin vận hành do Admin/Creator công bố.</p></article></div></section>
  {pass&&<section className="panel tnv-pass-result"><div><span className="eyebrow">ĐÃ XÁC THỰC</span><h2>{pass.game?.title||'Game được giao'}</h2><p>{pass.set?.title}</p></div><button className="primary-button" onClick={()=>navigate(`/host/${encodeURIComponent(token)}?pin=${encodeURIComponent(pin)}`)}>Mở Host Control</button></section>}
  <section className="tnv-media-section"><div className="section-heading"><div><span className="eyebrow">HOẠT ĐỘNG TNV</span><h2>Ảnh hoạt động & báo cáo</h2><p>Ảnh tải lên không công khai ngay. Admin cần duyệt trước khi đưa vào khu trưng bày.</p></div></div><div className="tnv-media-grid"><div className="panel media-upload-card"><ImagePlus/><h3>Tải ảnh hoạt động</h3><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f)setPreview(URL.createObjectURL(f))}}/>{preview&&<img src={preview} alt="Ảnh xem trước"/>}<button className="secondary-button full" disabled={!file||!token} onClick={upload}><UploadCloud/>Gửi ảnh chờ duyệt</button></div><div className="panel report-card"><ClipboardCheck/><h3>Báo cáo nhanh sau buổi</h3><textarea rows={9} value={report} onChange={e=>setReport(e.target.value)} placeholder="Ví dụ: số học viên tham gia, nội dung đã chơi, vấn đề phát sinh, đề xuất cho buổi sau…"/><button className="primary-button full" disabled={!token||!report.trim()} onClick={sendReport}>Gửi báo cáo</button></div></div></section>
  {gallery.length>0&&<section className="tnv-gallery"><div className="section-heading"><div><span className="eyebrow">TRƯNG BÀY HOẠT ĐỘNG</span><h2>Ảnh TNV đã được duyệt</h2><p>Chỉ những ảnh đã qua Admin review mới xuất hiện tại đây.</p></div></div><div className="tnv-gallery-grid">{gallery.map(x=><img key={x.id} src={x.media_url} alt="Hoạt động TNV"/>)}</div></section>}
  </main>
}
