import React from 'react';
import { ArrowLeft, CheckCircle2, XCircle, Trophy, RotateCcw, Lightbulb, Volume2, Pause, Play, Gauge, Headphones } from 'lucide-react';
import type { GameMode, Question, QuestionSet } from '../types';
import { navigate } from '../lib/router';

function normalize(s:string){return s.trim().toLocaleLowerCase().replace(/[.,!?。！？，]/g,'').replace(/\s+/g,' ')}
function isCorrect(q:Question,value:string){return q.answers.some(a=>normalize(a)===normalize(value))}

function AudioTrainer({q}:{q:Question}){
  const audioRef=React.useRef<HTMLAudioElement|null>(null);const [plays,setPlays]=React.useState(0);const [playing,setPlaying]=React.useState(false);const [rate,setRate]=React.useState(q.playbackRate||1);const [failed,setFailed]=React.useState(false);
  const max=q.maxPlays||99;const can=plays<max;
  const speak=()=>{if(!q.ttsText||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.ttsText);u.lang=q.ttsLang||'en-US';u.rate=rate;u.onend=()=>setPlaying(false);u.onerror=()=>setPlaying(false);setPlaying(true);setPlays(x=>x+1);window.speechSynthesis.speak(u)};
  const play=()=>{if(!can)return;if(audioRef.current&&!failed){audioRef.current.playbackRate=rate;audioRef.current.currentTime=0;audioRef.current.play().then(()=>{setPlays(x=>x+1);setPlaying(true)}).catch(()=>{setFailed(true);speak()});}else speak()};
  const pause=()=>{audioRef.current?.pause();if('speechSynthesis'in window)window.speechSynthesis.cancel();setPlaying(false)};
  return <div className="audio-trainer"><div className="audio-icon"><Headphones/></div><div className="audio-main"><strong>Listening</strong><span>{plays}/{max===99?'∞':max} lượt nghe</span><div className="audio-controls"><button onClick={playing?pause:play} disabled={!can&&!playing}>{playing?<Pause/>:<Play/>}{playing?'Tạm dừng':'Nghe'}</button><label><Gauge/> <select value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="0.75">0.75×</option><option value="1">1×</option><option value="1.15">1.15×</option><option value="1.3">1.3×</option></select></label></div>{q.mediaUrl&&<audio ref={audioRef} src={q.mediaUrl} preload="metadata" onEnded={()=>setPlaying(false)} onError={()=>setFailed(true)}/>}<small>{failed?'Audio file không tải được — hệ thống đang dùng TTS fallback.':'Audio file thật + TTS fallback khi cần.'}</small></div></div>
}

export function GamePlayer({set,mode}:{set:QuestionSet;mode:GameMode}){
 const [index,setIndex]=React.useState(0),[score,setScore]=React.useState(0),[streak,setStreak]=React.useState(0),[answer,setAnswer]=React.useState('');
 const [selected,setSelected]=React.useState<string[]>([]),[locked,setLocked]=React.useState(false),[wasCorrect,setWasCorrect]=React.useState(false),[finished,setFinished]=React.useState(false),[order,setOrder]=React.useState<string[]>([]),[matched,setMatched]=React.useState<Record<string,string>>({});
 const timed=['time-bomb','lightning-round','quick-fire','last-second'].includes(mode.id);const [timeLeft,setTimeLeft]=React.useState(timed?15:0);const compatible=set.questions.filter(q=>mode.supportedQuestionTypes.includes(q.type));const questions=compatible.length?compatible:set.questions;const q=questions[index];
 React.useEffect(()=>{if(q?.options&&['ordering','sentence_builder'].includes(q.type))setOrder([...q.options].sort(()=>Math.random()-.5));else setOrder([]);setMatched({});setTimeLeft(timed?15:0)},[index,q?.id,timed]);
 React.useEffect(()=>{if(!timed||locked||finished)return;const t=setInterval(()=>setTimeLeft(v=>{if(v<=1){setLocked(true);setStreak(0);return 0}return v-1}),1000);return()=>clearInterval(t)},[timed,locked,finished,index]);
 if(!q||finished){const max=Math.max(1,questions.length*100);const accuracy=Math.min(100,Math.round(score/max*100));return <main className="play-stage finish-stage"><div className="finish-card"><div className="finish-trophy"><Trophy/></div><span className="eyebrow">HOÀN THÀNH</span><h1>{mode.icon} {mode.name}</h1><p>{set.title}</p><div className="result-grid"><div><strong>{score}</strong><span>Điểm</span></div><div><strong>{accuracy}%</strong><span>Hiệu suất</span></div><div><strong>{questions.length}</strong><span>Câu</span></div></div><div className="button-row"><button className="primary-button" onClick={()=>{setIndex(0);setScore(0);setStreak(0);setFinished(false);setLocked(false);setAnswer('');setSelected([])}}><RotateCcw/>Chơi lại</button><button className="secondary-button" onClick={()=>navigate('/explore')}>Khám phá game khác</button></div></div></main>}
 const submit=(value?:string)=>{if(locked)return;let response=value??answer;let ok=false;if(['ordering','sentence_builder'].includes(q.type))response=order.join(' ');if(q.type==='matching'){ok=(q.pairs||[]).every(p=>normalize(matched[p.left]||'')===normalize(p.right));}else if(q.type==='multiple_select')ok=q.answers.length===selected.length&&q.answers.every(a=>selected.some(s=>normalize(s)===normalize(a)));else ok=isCorrect(q,response);setWasCorrect(ok);setLocked(true);const ns=ok?streak+1:0;setStreak(ns);if(ok){const diff=(q.difficulty||1)*8;const time=timed?timeLeft*2:0;setScore(s=>s+100+Math.min(ns*10,80)+diff+time)}};
 const next=()=>{if(index>=questions.length-1){setFinished(true);return}setIndex(i=>i+1);setAnswer('');setSelected([]);setLocked(false);setWasCorrect(false)};
 const render=()=>{if(q.type==='matching'&&q.pairs)return <div className="matching-grid">{q.pairs.map(p=><div className="match-row" key={p.left}><strong>{p.left}</strong><select value={matched[p.left]||''} disabled={locked} onChange={e=>setMatched(m=>({...m,[p.left]:e.target.value}))}><option value="">Chọn…</option>{[...q.pairs!].sort(()=>Math.random()-.5).map(x=><option key={x.right}>{x.right}</option>)}</select></div>)}</div>;if(['ordering','sentence_builder'].includes(q.type)&&q.options)return <div className="order-box"><p className="muted">Chạm thẻ để đẩy nó sang trái.</p><div className="token-row">{order.map((t,i)=><button className="token" disabled={locked} key={i} onClick={()=>{if(i===0)return;const c=[...order];[c[i-1],c[i]]=[c[i],c[i-1]];setOrder(c)}}>{t}</button>)}</div></div>;if(q.options?.length)return <div className="answer-grid">{q.options.map((o,i)=>{const sel=selected.includes(o)||answer===o;let cls='answer-button'+(sel?' selected':'');if(locked){if(isCorrect(q,o))cls+=' correct';else if(sel)cls+=' wrong'}return <button className={cls} disabled={locked} key={o} onClick={()=>{if(q.type==='multiple_select')setSelected(s=>s.includes(o)?s.filter(x=>x!==o):[...s,o]);else{setAnswer(o);submit(o)}}}><span>{String.fromCharCode(65+i)}</span>{o}</button>})}</div>;return <div className="typed-wrap"><input autoFocus disabled={locked} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&answer&&submit()} placeholder="Nhập câu trả lời…"/><button className="primary-button" disabled={!answer||locked} onClick={()=>submit()}>Trả lời</button></div>};
 const needsAudio=['audio_choice','listening_input','dictation'].includes(q.type)||q.mediaType==='audio'||!!q.ttsText;
 return <main className={`play-stage mechanic-${mode.mechanic}`} style={{'--game-accent':mode.color} as React.CSSProperties}><div className="play-shell"><div className="play-topline"><button className="icon-button" onClick={()=>navigate('/explore')}><ArrowLeft/></button><div className="play-title"><span>{mode.icon}</span><div><strong>{mode.name}</strong><small>{set.title}</small></div></div><div className="score-pill"><span>{streak>1?`🔥 ${streak}x`:'Điểm'}</span><strong>{score}</strong></div></div><div className="progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div><ModeHud mode={mode} score={score} index={index} total={questions.length} streak={streak} timeLeft={timeLeft}/><section className="question-panel"><div className="question-meta"><span>CÂU {index+1}/{questions.length}</span><span>Độ khó {q.difficulty||1}/5</span><span>{q.type.replaceAll('_',' ')}</span></div>{needsAudio&&<AudioTrainer q={q}/>} {q.mediaUrl&&q.mediaType==='image'&&<div className="question-media"><img src={q.mediaUrl} alt="Question media"/></div>}{q.context&&<div className="context-box">{q.context}</div>}{q.passage&&<div className="passage-box">{q.passage}</div>}<h1>{q.prompt}</h1>{q.hint&&<div className="hint"><Lightbulb/>{q.hint}</div>}{render()}{!locked&&(q.type==='matching'||q.type==='multiple_select'||['ordering','sentence_builder'].includes(q.type))&&<button className="primary-button submit-wide" onClick={()=>submit()}>Chốt đáp án</button>}{locked&&<div className={wasCorrect?'feedback correct':'feedback wrong'}>{wasCorrect?<CheckCircle2/>:<XCircle/>}<div><strong>{wasCorrect?'Chính xác!':'Chưa đúng'}</strong>{!wasCorrect&&<p>Đáp án: {q.answers.join(' / ')}</p>}{q.explanation&&<p>{q.explanation}</p>}{q.transcript&&needsAudio&&<details><summary>Xem transcript</summary><p>{q.transcript}</p></details>}</div><button onClick={next}>{index===questions.length-1?'Xem kết quả':'Câu tiếp →'}</button></div>}</section></div></main>
}

function ModeHud({mode,score,index,total,streak,timeLeft}:{mode:GameMode;score:number;index:number;total:number;streak:number;timeLeft:number}){const progress=Math.min(100,Math.round(((index+1)/Math.max(total,1))*100));if(mode.mechanic==='race')return <div className="mode-hud race-hud"><span>🏁</span><div><i style={{width:`${progress}%`}}/><b style={{left:`calc(${progress}% - 14px)`}}>{mode.icon}</b></div><span>🏆</span></div>;if(['survival','tower'].includes(mode.mechanic))return <div className="mode-hud timer-hud"><span>{mode.mechanic==='tower'?'🛡️':'💣'}</span><strong>{timeLeft||Math.max(1,10-index)}{timeLeft?'s':' HP'}</strong><div><i style={{width:`${timeLeft?Math.max(0,timeLeft/15*100):100-progress/2}%`}}/></div><em>{streak>1?`${streak}x combo`:'Giữ nhịp!'}</em></div>;if(mode.mechanic==='board')return <div className="mode-hud board-hud">{Array.from({length:8}).map((_,i)=><span className={i<Math.ceil(progress/12.5)?'open':''} key={i}>{i===7?'🏆':'◆'}</span>)}</div>;if(mode.mechanic==='economy')return <div className="mode-hud economy-hud"><span>🪙 {Math.floor(score/10)}</span><span>🎒 Lv.{Math.max(1,Math.floor(score/250)+1)}</span><span>🔥 {streak}</span></div>;return <div className="mode-hud standard-hud"><span>{mode.icon}</span><strong>{progress}%</strong><small>{mode.mechanic.toUpperCase()}</small></div>}
