import React from 'react';
import { ArrowLeft, CheckCircle2, XCircle, Trophy, RotateCcw, Lightbulb, Pause, Play, Gauge, Headphones, BookOpenCheck, GraduationCap, LogOut, ArrowRight, ListChecks } from 'lucide-react';
import type { GameMode, Question, QuestionSet } from '../types';
import { navigate } from '../lib/router';

function normalize(s:string){return s.trim().toLocaleLowerCase().replace(/[.,!?。！？，]/g,'').replace(/\s+/g,' ')}
function isCorrect(q:Question,value:string){return q.answers.some(a=>normalize(a)===normalize(value))}
function shuffle<T>(arr:T[]){return [...arr].sort(()=>Math.random()-.5)}
function sessionQuestions(base:Question[],target=24){
  if(!base.length)return [];
  const pool:Question[]=[]; let round=0;
  while(pool.length<Math.max(20,target)){
    const batch=shuffle(base).map((q,i)=>({...q,id:`${q.id}__${round}_${i}`,options:q.options?shuffle(q.options):q.options,tags:[...(q.tags||[]),round?'reinforcement':'first-pass']}));
    pool.push(...batch);round++;
  }
  return pool.slice(0,Math.min(30,Math.max(24,target)));
}

type Attempt={question:Question;correct:boolean;response:string};
type Phase='play'|'summary'|'review'|'relearn'|'retest'|'final';

function AudioTrainer({q}:{q:Question}){
  const audioRef=React.useRef<HTMLAudioElement|null>(null); const [plays,setPlays]=React.useState(0); const [playing,setPlaying]=React.useState(false); const [rate,setRate]=React.useState(q.playbackRate||1); const [failed,setFailed]=React.useState(false);
  const max=q.maxPlays||99; const can=plays<max;
  const speak=()=>{if(!q.ttsText||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.ttsText);u.lang=q.ttsLang||'en-US';u.rate=rate;u.onend=()=>setPlaying(false);u.onerror=()=>setPlaying(false);setPlaying(true);setPlays(x=>x+1);window.speechSynthesis.speak(u)};
  const play=()=>{if(!can)return;if(audioRef.current&&!failed){audioRef.current.playbackRate=rate;audioRef.current.currentTime=0;audioRef.current.play().then(()=>{setPlays(x=>x+1);setPlaying(true)}).catch(()=>{setFailed(true);speak()})}else speak()};
  const pause=()=>{audioRef.current?.pause();if('speechSynthesis'in window)window.speechSynthesis.cancel();setPlaying(false)};
  return <div className="audio-trainer"><div className="audio-icon"><Headphones/></div><div className="audio-main"><strong>Listening</strong><span>{plays}/{max===99?'∞':max} lượt nghe</span><div className="audio-controls"><button onClick={playing?pause:play} disabled={!can&&!playing}>{playing?<Pause/>:<Play/>}{playing?'Tạm dừng':'Nghe'}</button><label><Gauge/><select value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="0.75">0.75×</option><option value="1">1×</option><option value="1.15">1.15×</option><option value="1.3">1.3×</option></select></label></div>{q.mediaUrl&&<audio ref={audioRef} src={q.mediaUrl} preload="metadata" onEnded={()=>setPlaying(false)} onError={()=>setFailed(true)}/>}<small>{failed?'Audio file không tải được — đang dùng TTS fallback.':'Audio file thật + TTS fallback khi cần.'}</small></div></div>
}

export function GamePlayer({set,mode}:{set:QuestionSet;mode:GameMode}){
  const compatible=React.useMemo(()=>{const c=set.questions.filter(q=>mode.supportedQuestionTypes.includes(q.type));return c.length?c:set.questions},[set,mode]);
  const initialQuestions=React.useMemo(()=>sessionQuestions(compatible,24),[compatible,set.id,mode.id]);
  const [phase,setPhase]=React.useState<Phase>('play'); const [questions,setQuestions]=React.useState<Question[]>(initialQuestions); const [index,setIndex]=React.useState(0); const [score,setScore]=React.useState(0); const [streak,setStreak]=React.useState(0); const [answer,setAnswer]=React.useState(''); const [selected,setSelected]=React.useState<string[]>([]); const [locked,setLocked]=React.useState(false); const [wasCorrect,setWasCorrect]=React.useState(false); const [order,setOrder]=React.useState<string[]>([]); const [matched,setMatched]=React.useState<Record<string,string>>({}); const [attempts,setAttempts]=React.useState<Attempt[]>([]); const [reviewIndex,setReviewIndex]=React.useState(0);
  const timed=['time-bomb','lightning-round','quick-fire','last-second'].includes(mode.id); const [timeLeft,setTimeLeft]=React.useState(timed?15:0); const q=questions[index];
  React.useEffect(()=>{setQuestions(initialQuestions);setIndex(0);setPhase('play');setAttempts([]);setScore(0);setStreak(0)},[initialQuestions]);
  React.useEffect(()=>{if(q?.options&&['ordering','sentence_builder'].includes(q.type))setOrder(shuffle(q.options));else setOrder([]);setMatched({});setTimeLeft(timed?15:0)},[index,q?.id,timed]);
  React.useEffect(()=>{if(!timed||locked||phase!=='play'&&phase!=='retest')return;const t=setInterval(()=>setTimeLeft(v=>{if(v<=1){setLocked(true);setStreak(0);return 0}return v-1}),1000);return()=>clearInterval(t)},[timed,locked,phase,index]);
  const wrong=attempts.filter(a=>!a.correct);
  const resetInputs=()=>{setAnswer('');setSelected([]);setLocked(false);setWasCorrect(false);setMatched({})};
  const startMain=()=>{setQuestions(sessionQuestions(compatible,24));setIndex(0);setScore(0);setStreak(0);setAttempts([]);setPhase('play');resetInputs()};
  const startRetest=()=>{const source=wrong.length?wrong.map(a=>({...a.question,id:`${a.question.id}_retry`})):compatible;const extra=shuffle(compatible).slice(0,Math.max(4,12-source.length));setQuestions(shuffle([...source,...extra]).slice(0,Math.max(8,Math.min(20,source.length+extra.length))));setIndex(0);setAttempts([]);setScore(0);setStreak(0);setPhase('retest');resetInputs()};
  const submit=(value?:string)=>{if(locked||!q)return;let response=value??answer;let ok=false;if(['ordering','sentence_builder'].includes(q.type))response=order.join(' ');if(q.type==='matching')ok=(q.pairs||[]).every(p=>normalize(matched[p.left]||'')===normalize(p.right));else if(q.type==='multiple_select')ok=q.answers.length===selected.length&&q.answers.every(a=>selected.some(s=>normalize(s)===normalize(a)));else ok=isCorrect(q,response);setWasCorrect(ok);setLocked(true);setAttempts(a=>[...a,{question:q,correct:ok,response}]);const ns=ok?streak+1:0;setStreak(ns);if(ok){const diff=(q.difficulty||1)*8;const time=timed?timeLeft*2:0;setScore(s=>s+100+Math.min(ns*10,80)+diff+time)}};
  const next=()=>{if(index>=questions.length-1){setPhase(phase==='retest'?'final':'summary');return}setIndex(i=>i+1);resetInputs()};
  const accuracy=attempts.length?Math.round(attempts.filter(a=>a.correct).length/attempts.length*100):0;
  if(phase==='summary')return <ResultSummary mode={mode} set={set} score={score} attempts={attempts} accuracy={accuracy} onReview={()=>{setReviewIndex(0);setPhase('review')}} onRelearn={()=>{setReviewIndex(0);setPhase('relearn')}} onRetry={startMain}/>;
  if(phase==='review'||phase==='relearn'){
    const items=phase==='review'?attempts:wrong; const item=items[reviewIndex];
    if(!item)return <main className="play-stage finish-stage"><div className="finish-card"><BookOpenCheck className="big-result-icon"/><h1>Không có câu sai cần học lại</h1><p>Bạn có thể chuyển thẳng sang kiểm tra lại hoặc hoàn tất.</p><div className="button-row"><button className="primary-button" onClick={startRetest}>Kiểm tra lại</button><button className="secondary-button" onClick={()=>navigate('/explore')}>Thoát</button></div></div></main>;
    return <main className="play-stage review-stage"><div className="review-shell"><div className="play-topline"><button className="icon-button" onClick={()=>setPhase('summary')}><ArrowLeft/></button><div className="play-title"><BookOpenCheck/><div><strong>{phase==='review'?'Xem lại bài':'Học lại câu sai'}</strong><small>{reviewIndex+1}/{items.length}</small></div></div></div><section className="question-panel review-card"><span className={item.correct?'review-status correct':'review-status wrong'}>{item.correct?'Đã trả lời đúng':'Cần học lại'}</span><h1>{item.question.prompt}</h1>{item.question.mediaType==='audio'&&<AudioTrainer q={item.question}/>}<div className="review-answer-grid"><div><small>Bạn đã trả lời</small><strong>{item.response||'Không có câu trả lời'}</strong></div><div><small>Đáp án đúng</small><strong>{item.question.answers.join(' / ')}</strong></div></div>{item.question.explanation&&<div className="explain-box"><Lightbulb/><p>{item.question.explanation}</p></div>}{item.question.hint&&<p className="muted">Gợi ý ghi nhớ: {item.question.hint}</p>}<div className="button-row review-actions">{reviewIndex>0&&<button className="secondary-button" onClick={()=>setReviewIndex(i=>i-1)}>← Trước</button>}{reviewIndex<items.length-1?<button className="primary-button" onClick={()=>setReviewIndex(i=>i+1)}>Tiếp theo <ArrowRight/></button>:<><button className="primary-button" onClick={startRetest}><GraduationCap/>Kiểm tra lại</button><button className="secondary-button" onClick={()=>navigate('/explore')}><LogOut/>Thoát</button></>}</div></section></div></main>
  }
  if(phase==='final')return <main className="play-stage finish-stage"><div className="finish-card mastery-card"><GraduationCap className="big-result-icon"/><span className="eyebrow">KIỂM TRA LẠI HOÀN TẤT</span><h1>{accuracy>=85?'Đã vững':'Cần ôn lại'}</h1><p>{set.title}</p><div className="result-grid"><div><strong>{accuracy}%</strong><span>Độ chính xác</span></div><div><strong>{attempts.filter(a=>a.correct).length}</strong><span>Câu đúng</span></div><div><strong>{attempts.filter(a=>!a.correct).length}</strong><span>Còn sai</span></div></div><div className="mastery-meter"><i style={{width:`${accuracy}%`}}/></div><div className="button-row stacked-mobile"><button className="primary-button" onClick={()=>accuracy>=85?navigate('/quick-play'):startRetest()}>{accuracy>=85?'Học phần tiếp theo':'Học lại phần chưa vững'}</button><button className="secondary-button" onClick={()=>navigate('/explore')}><LogOut/>Hoàn tất & thoát</button></div></div></main>;
  if(!q)return null;
  const render=()=>{if(q.type==='matching'&&q.pairs)return <div className="matching-grid">{q.pairs.map(p=><div className="match-row" key={p.left}><strong>{p.left}</strong><select value={matched[p.left]||''} disabled={locked} onChange={e=>setMatched(m=>({...m,[p.left]:e.target.value}))}><option value="">Chọn…</option>{shuffle(q.pairs!).map(x=><option key={x.right}>{x.right}</option>)}</select></div>)}</div>;if(['ordering','sentence_builder'].includes(q.type)&&q.options)return <div className="order-box"><p className="muted">Chạm thẻ để đẩy nó sang trái.</p><div className="token-row">{order.map((t,i)=><button className="token" disabled={locked} key={`${t}-${i}`} onClick={()=>{if(i===0)return;const c=[...order];[c[i-1],c[i]]=[c[i],c[i-1]];setOrder(c)}}>{t}</button>)}</div></div>;if(q.options?.length)return <div className="answer-grid">{q.options.map((o,i)=>{const sel=selected.includes(o)||answer===o;let cls='answer-button'+(sel?' selected':'');if(locked){if(isCorrect(q,o))cls+=' correct';else if(sel)cls+=' wrong'}return <button className={cls} disabled={locked} key={`${o}-${i}`} onClick={()=>{if(q.type==='multiple_select')setSelected(s=>s.includes(o)?s.filter(x=>x!==o):[...s,o]);else{setAnswer(o);submit(o)}}}><span>{String.fromCharCode(65+i)}</span>{o}</button>})}</div>;return <div className="typed-wrap"><input autoFocus disabled={locked} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&answer&&submit()} placeholder="Nhập câu trả lời…"/><button className="primary-button" disabled={!answer||locked} onClick={()=>submit()}>Trả lời</button></div>};
  const needsAudio=['audio_choice','listening_input','dictation'].includes(q.type)||q.mediaType==='audio'||!!q.ttsText;
  return <main className={`play-stage mechanic-${mode.mechanic}`} style={{'--game-accent':mode.color} as React.CSSProperties}><div className="play-shell"><div className="play-topline"><button className="icon-button" onClick={()=>navigate('/explore')}><ArrowLeft/></button><div className="play-title"><span>{mode.icon}</span><div><strong>{phase==='retest'?'Kiểm tra lại':mode.name}</strong><small>{set.title}</small></div></div><div className="score-pill"><span>{streak>1?`🔥 ${streak}x`:'Điểm'}</span><strong>{score}</strong></div></div><div className="progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div><ModeHud mode={mode} score={score} index={index} total={questions.length} streak={streak} timeLeft={timeLeft}/><section className="question-panel"><div className="question-meta"><span>CÂU {index+1}/{questions.length}</span><span>{phase==='retest'?'RETEST':'20–30 CÂU/BÀI'}</span><span>Độ khó {q.difficulty||1}/5</span></div>{needsAudio&&<AudioTrainer q={q}/>} {q.mediaUrl&&q.mediaType==='image'&&<div className="question-media"><img src={q.mediaUrl} alt="Question media"/></div>}{q.context&&<div className="context-box">{q.context}</div>}{q.passage&&<div className="passage-box">{q.passage}</div>}<h1>{q.prompt}</h1>{q.hint&&<div className="hint"><Lightbulb/>{q.hint}</div>}{render()}{!locked&&(q.type==='matching'||q.type==='multiple_select'||['ordering','sentence_builder'].includes(q.type))&&<button className="primary-button submit-wide" onClick={()=>submit()}>Chốt đáp án</button>}{locked&&<div className={wasCorrect?'feedback correct':'feedback wrong'}>{wasCorrect?<CheckCircle2/>:<XCircle/>}<div><strong>{wasCorrect?'Chính xác!':'Chưa đúng'}</strong>{!wasCorrect&&<p>Đáp án: {q.answers.join(' / ')}</p>}{q.explanation&&<p>{q.explanation}</p>}</div><button onClick={next}>{index===questions.length-1?'Xem kết quả':'Câu tiếp →'}</button></div>}</section></div></main>
}

function ResultSummary({mode,set,score,attempts,accuracy,onReview,onRelearn,onRetry}:{mode:GameMode;set:QuestionSet;score:number;attempts:Attempt[];accuracy:number;onReview:()=>void;onRelearn:()=>void;onRetry:()=>void}){const wrong=attempts.filter(a=>!a.correct);return <main className="play-stage finish-stage"><div className="finish-card result-expanded"><div className="finish-trophy"><Trophy/></div><span className="eyebrow">HOÀN THÀNH VÒNG CHÍNH</span><h1>{mode.icon} {mode.name}</h1><p>{set.title}</p><div className="result-grid"><div><strong>{score}</strong><span>Điểm</span></div><div><strong>{accuracy}%</strong><span>Độ chính xác</span></div><div><strong>{attempts.length}</strong><span>Tổng câu</span></div><div><strong>{wrong.length}</strong><span>Cần học lại</span></div></div><div className="learning-path"><article className="done"><CheckCircle2/><b>1. Chơi</b><span>Đã hoàn thành {attempts.length} câu</span></article><article><ListChecks/><b>2. Xem lại</b><span>Kiểm tra từng đáp án</span></article><article><BookOpenCheck/><b>3. Học lại</b><span>Tập trung câu sai</span></article><article><GraduationCap/><b>4. Kiểm tra lại</b><span>Xác nhận đã hiểu</span></article></div><div className="button-row multi-actions"><button className="primary-button" onClick={onReview}><ListChecks/>Xem lại bài</button><button className="secondary-button" onClick={onRelearn}><BookOpenCheck/>Học lại câu sai</button><button className="secondary-button" onClick={onRetry}><RotateCcw/>Chơi lại</button><button className="ghost-button" onClick={()=>navigate('/explore')}><LogOut/>Thoát</button></div></div></main>}

function ModeHud({mode,score,index,total,streak,timeLeft}:{mode:GameMode;score:number;index:number;total:number;streak:number;timeLeft:number}){const progress=Math.min(100,Math.round(((index+1)/Math.max(total,1))*100));if(mode.mechanic==='race')return <div className="mode-hud race-hud"><span>🏁</span><div><i style={{width:`${progress}%`}}/><b style={{left:`calc(${progress}% - 14px)`}}>{mode.icon}</b></div><span>🏆</span></div>;if(['survival','tower'].includes(mode.mechanic))return <div className="mode-hud timer-hud"><span>{mode.mechanic==='tower'?'🛡️':'💣'}</span><strong>{timeLeft||Math.max(1,10-index)}{timeLeft?'s':' HP'}</strong><div><i style={{width:`${timeLeft?Math.max(0,timeLeft/15*100):100-progress/2}%`}}/></div><em>{streak>1?`${streak}x combo`:'Giữ nhịp!'}</em></div>;if(mode.mechanic==='board')return <div className="mode-hud board-hud">{Array.from({length:8}).map((_,i)=><span className={i<Math.ceil(progress/12.5)?'open':''} key={i}>{i===7?'🏆':'◆'}</span>)}</div>;if(mode.mechanic==='economy')return <div className="mode-hud economy-hud"><span>🪙 {Math.floor(score/10)}</span><span>🎒 Lv.{Math.max(1,Math.floor(score/250)+1)}</span><span>🔥 {streak}</span></div>;return <div className="mode-hud standard-hud"><span>{mode.icon}</span><strong>{progress}%</strong><small>{mode.mechanic.toUpperCase()}</small></div>}
